/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 map.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('assets/scenes/map.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[25.752, -1.647, -25.932]} rotation={[Math.PI / 2, 0, -2.564]} scale={0.002}>
        <mesh geometry={nodes.Mesh009.geometry} material={materials['Montagne orange']} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.Border} />
      </group>
      <mesh geometry={nodes.Cube175.geometry} material={materials['Material.013']} position={[-17.244, 0.838, 12.543]} rotation={[0, -0.698, -0.001]} scale={[0.02, 0.416, -0.261]} />
      <mesh geometry={nodes.Base095.geometry} material={nodes.Base095.material} position={[-8.528, 4.261, 1.454]} rotation={[Math.PI / 2, 0, -0.181]} scale={[0.623, 0.621, 0.372]} />
      <group position={[-7.21, 0.511, -8.314]} rotation={[-Math.PI, 0.812, -Math.PI]} scale={0.244}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.ban} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.Ban2} />
      </group>
      <mesh geometry={nodes.Hand.geometry} material={materials['Material.002']} position={[-8.027, 0.804, -7.915]} rotation={[-2.4, 0.661, 2.629]} scale={[0.268, 0.186, 0.186]} />
      <group position={[-7.65, 1.133, -7.921]} rotation={[-Math.PI, 0.812, -Math.PI]} scale={[0.033, 0.089, 0.008]}>
        <mesh geometry={nodes.Cube088.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube088_1.geometry} material={materials['Material.014']} />
      </group>
      <mesh geometry={nodes.Cube098.geometry} material={materials['Material.017']} position={[-7.045, 0.835, -8.474]} rotation={[-Math.PI, 0.812, -Math.PI]} scale={[0.042, 0.08, 0.016]} />
      <group position={[-7.784, 1.203, -8.048]} rotation={[-Math.PI / 2, 0, 2.329]} scale={0.028}>
        <mesh geometry={nodes.Circle003.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials['Material.020']} />
      </group>
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.016']} position={[-7.742, 1.203, -8.005]} rotation={[-Math.PI / 2, 0, 2.329]} scale={0.028} />
      <mesh geometry={nodes.Chasis.geometry} material={materials['Material.023']} position={[-7.957, 0.511, -7.777]} rotation={[-Math.PI, 0.812, -Math.PI]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('assets/scenes/map.glb')
