/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.10 map1.glb --transform
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function Model({ onPointerUp }) {
  const { nodes, materials } = useGLTF("assets/scenes/map.glb")
  return (
    <group onPointerUp={onPointerUp} dispose={null}>
      <group position={[0.03, -1.37, -81.67]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_1.geometry}
          material={materials.Ground}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_2.geometry}
          material={materials["Lush grass"]}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_3.geometry}
          material={materials["Castle n pillar"]}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_4.geometry}
          material={materials["Pine tree"]}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_5.geometry}
          material={materials["Stump tree"]}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_6.geometry}
          material={materials["Grass 1"]}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_7.geometry}
          material={materials.Veins}
        />
        <mesh
          geometry={nodes.Isometric_Game_Level_Low_Poly_8.geometry}
          material={materials.Stones}
        />
      </group>
      <mesh
        geometry={nodes.Savanna025.geometry}
        material={materials["Water.001"]}
        position={[9.13, -0.03, -3.52]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna029.geometry}
        material={materials["Grass02.001"]}
        position={[-2.89, -0.62, -15.82]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna011.geometry}
        material={materials["Grass02.001"]}
        position={[-2.55, 0.11, -16.2]}
        scale={-18.57}
      />
      <group position={[-11.8, 1.34, -5.2]} scale={14.79}>
        <mesh geometry={nodes.Plane036.geometry} material={materials["Aloe_body.001"]} />
        <mesh geometry={nodes.Plane036_1.geometry} material={materials["Aloe_leaves.001"]} />
        <mesh geometry={nodes.Plane036_2.geometry} material={materials["Aloe_spike.001"]} />
      </group>
      <group position={[6.57, 0.37, -3.24]} scale={14.79}>
        <mesh geometry={nodes.Plane037.geometry} material={materials["Aloe_body.001"]} />
        <mesh geometry={nodes.Plane037_1.geometry} material={materials["Aloe_leaves.001"]} />
        <mesh geometry={nodes.Plane037_2.geometry} material={materials["Aloe_spike.001"]} />
      </group>
      <mesh
        geometry={nodes.Savanna032.geometry}
        material={materials["Bush03.001"]}
        position={[12.52, 0.41, -6.72]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna033.geometry}
        material={materials["Bush03.001"]}
        position={[1.72, 0.06, -11.54]}
        scale={14.79}
      />
      <group position={[7.76, 0.37, -20.63]} scale={14.79}>
        <mesh geometry={nodes.Plane040.geometry} material={materials["Aloe_body.001"]} />
        <mesh geometry={nodes.Plane040_1.geometry} material={materials["Aloe_leaves.001"]} />
        <mesh geometry={nodes.Plane040_2.geometry} material={materials["Aloe_spike.001"]} />
      </group>
      <mesh
        geometry={nodes.Savanna035.geometry}
        material={materials["Bush03.001"]}
        position={[5.87, 0.06, -21.29]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna036.geometry}
        material={materials["Rock.001"]}
        position={[18.22, 0.11, -49.15]}
        scale={14.79}
      />
      <group position={[-8.9, 3.27, -33.4]} scale={14.79}>
        <mesh geometry={nodes.Plane043.geometry} material={materials["Grass and greenery.001"]} />
        <mesh geometry={nodes.Plane043_1.geometry} material={materials["Wood.001"]} />
      </group>
      <mesh
        geometry={nodes.Savanna038.geometry}
        material={materials["Bush_colour_01.001"]}
        position={[34.1, 0.11, -48.12]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna039.geometry}
        material={materials["Bush_color_02.001"]}
        position={[33.01, 0.42, -49.74]}
        scale={14.79}
      />
      <group position={[11.49, 0.03, -27.62]} scale={14.79}>
        <mesh geometry={nodes.Plane046.geometry} material={materials["Rhino_skin.001"]} />
        <mesh geometry={nodes.Plane046_1.geometry} material={materials["Shadow.001"]} />
        <mesh geometry={nodes.Plane046_2.geometry} material={materials["Aloe_spike.001"]} />
        <mesh geometry={nodes.Plane046_3.geometry} material={materials["Rhino_hoof.001"]} />
      </group>
      <group position={[8, 1.18, -24.06]} scale={14.79}>
        <mesh geometry={nodes.Plane047.geometry} material={materials["Rhino_skin.001"]} />
        <mesh geometry={nodes.Plane047_1.geometry} material={materials["Shadow.001"]} />
        <mesh geometry={nodes.Plane047_2.geometry} material={materials["Aloe_spike.001"]} />
        <mesh geometry={nodes.Plane047_3.geometry} material={materials["Rhino_hoof.001"]} />
      </group>
      <mesh
        geometry={nodes.Savanna042.geometry}
        material={materials["Rock.001"]}
        position={[-0.17, -0.63, -14.11]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna043.geometry}
        material={materials["Rock.001"]}
        position={[27.69, -0.62, -47.81]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna044.geometry}
        material={materials["Rock.001"]}
        position={[25.97, -0.28, -46.45]}
        scale={14.79}
      />
      <group position={[5.16, -0.18, -1.98]} scale={14.79}>
        <mesh geometry={nodes.Plane051.geometry} material={materials["Aloe_body.001"]} />
        <mesh geometry={nodes.Plane051_1.geometry} material={materials["Aloe_leaves.001"]} />
        <mesh geometry={nodes.Plane051_2.geometry} material={materials["Aloe_spike.001"]} />
      </group>
      <mesh
        geometry={nodes.Savanna046.geometry}
        material={materials["Bush03.001"]}
        position={[-12.05, 0.06, -24.95]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna047.geometry}
        material={materials["Bush_color_02.001"]}
        position={[-9.49, 0.42, -24.9]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna048.geometry}
        material={materials["Rock.001"]}
        position={[-11.52, -0.63, -24.08]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna049.geometry}
        material={materials["Bush03.001"]}
        position={[-10.93, 0.75, -17.09]}
        scale={14.79}
      />
      <group position={[11.04, 3.35, -35.16]} scale={14.79}>
        <mesh geometry={nodes.Plane056.geometry} material={materials["Fa_szín_02.001"]} />
        <mesh geometry={nodes.Plane056_1.geometry} material={materials["Tree_leafs.001"]} />
      </group>
      <mesh
        geometry={nodes.Savanna051.geometry}
        material={materials["Rock.001"]}
        position={[-2.82, -0.43, -21.17]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna052.geometry}
        material={materials["Bush_colour_01.001"]}
        position={[26.74, 0.35, -64.68]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna053.geometry}
        material={materials["Rock.001"]}
        position={[-8.41, -0.59, -3.76]}
        scale={14.79}
      />
      <mesh
        geometry={nodes.Savanna054.geometry}
        material={materials["Rock.001"]}
        position={[-8.77, -0.61, -4.17]}
        scale={14.79}
      />
      <group position={[1.05, -1.68, -11.86]} scale={14.79}>
        <mesh geometry={nodes.Plane061.geometry} material={materials["Earth.001"]} />
        <mesh geometry={nodes.Plane061_1.geometry} material={materials["Earth.001"]} />
        <mesh geometry={nodes.Plane061_2.geometry} material={materials["Water.001"]} />
      </group>
      <group position={[-1.36, -0.66, -12.85]} rotation={[0, 0.87, 0]} scale={2.42}>
        <mesh geometry={nodes.Cube001.geometry} material={materials["Tree_body02.001"]} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials["Aloe_body.001"]} />
      </group>
      <mesh
        geometry={nodes.rock03017.geometry}
        material={materials["rock03.001"]}
        position={[1.19, 2.52, -81.6]}
        rotation={[0, -0.04, 0]}
        scale={[1.23, 0.35, 0.46]}
      />
      <mesh
        geometry={nodes.rock03021.geometry}
        material={materials["rock03.001"]}
        position={[2.92, 2.52, -75.51]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[1.23, 0.35, 0.46]}
      />
      <mesh
        geometry={nodes.rock03018.geometry}
        material={materials["rock03.001"]}
        position={[-0.17, -0.04, -78.71]}
        rotation={[Math.PI / 2, 0, 0.83]}
        scale={[0.47, 1.17, 0.24]}
      />
      <mesh
        geometry={nodes.rock03019.geometry}
        material={materials["rock03.001"]}
        position={[6.12, -0.04, -74.84]}
        rotation={[Math.PI / 2, 0, -1.42]}
        scale={[0.47, 1.17, 0.24]}
      />
      <mesh
        geometry={nodes.rock03032.geometry}
        material={materials["rock03.001"]}
        position={[-2.97, -0.04, -80.71]}
        rotation={[Math.PI / 2, 0, 0.63]}
        scale={[0.47, 1.17, 0.24]}
      />
      <mesh
        geometry={nodes.rock03033.geometry}
        material={materials["rock03.001"]}
        position={[6.12, 0.5, -74.35]}
        rotation={[1.98, 0.16, -0.03]}
        scale={[0.47, 1.17, 0.24]}
      />
      <mesh
        geometry={nodes.rock03020.geometry}
        material={materials["rock03.001"]}
        position={[5.11, 2.47, -77.71]}
        rotation={[0, Math.PI / 3, 0]}
        scale={[1.21, 0.29, 0.49]}
      />
      <mesh
        geometry={nodes.rock03022.geometry}
        material={materials["rock03.001"]}
        position={[-0.08, 2.45, -74.71]}
        scale={[1.23, 0.27, 0.49]}
      />
      <mesh
        geometry={nodes.rock03023.geometry}
        material={materials["rock03.001"]}
        position={[-3.08, 2.41, -75.51]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={[1.17, 0.3, 0.48]}
      />
      <mesh
        geometry={nodes.rock03024.geometry}
        material={materials["rock03.001"]}
        position={[-5.28, 2.46, -77.71]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={[1.16, 0.32, 0.48]}
      />
      <mesh
        geometry={nodes.rock03025.geometry}
        material={materials["rock03.001"]}
        position={[-6.08, 2.43, -80.71]}
        rotation={[0, -1.57, 0]}
        scale={[1.22, 0.26, 0.49]}
      />
      <mesh
        geometry={nodes.rock03026.geometry}
        material={materials["rock03.001"]}
        position={[-5.28, 2.47, -83.71]}
        rotation={[Math.PI, -Math.PI / 3, Math.PI]}
        scale={[1.21, 0.33, 0.54]}
      />
      <mesh
        geometry={nodes.rock03027.geometry}
        material={materials["rock03.001"]}
        position={[-3.08, 2.43, -85.9]}
        rotation={[Math.PI, -Math.PI / 6, Math.PI]}
        scale={[1.18, 0.28, 0.47]}
      />
      <mesh
        geometry={nodes.rock03028.geometry}
        material={materials["rock03.001"]}
        position={[-0.08, 2.49, -86.71]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.15, 0.32, 0.55]}
      />
      <mesh
        geometry={nodes.rock03029.geometry}
        material={materials["rock03.001"]}
        position={[2.92, 2.5, -85.9]}
        rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
        scale={[1.19, 0.32, 0.53]}
      />
      <mesh
        geometry={nodes.rock03030.geometry}
        material={materials["rock03.001"]}
        position={[5.11, 2.47, -83.71]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={[1.23, 0.33, 0.45]}
      />
      <mesh
        geometry={nodes.rock03031.geometry}
        material={materials["rock03.001"]}
        position={[5.92, 2.42, -80.71]}
        rotation={[0, 1.57, 0]}
        scale={[1.17, 0.27, 0.45]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Castle n pillar"]}
        position={[4.99, -0.91, -51.18]}
        scale={[1, 0.76, 1]}
      />
      <mesh
        geometry={nodes.polySurface205001.geometry}
        material={materials["mat.002"]}
        position={[27.63, -0.61, -52.25]}
        rotation={[Math.PI / 2, 0, 2.16]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Mineral002.geometry}
        material={materials["Material.004"]}
        position={[16.99, 0.51, -61.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.Mineral005.geometry}
        material={materials["Material.004"]}
        position={[33.79, 0.51, -63.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.Mineral006.geometry}
        material={materials["Material.004"]}
        position={[33.79, 0.51, -65.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.Mineral007.geometry}
        material={materials["Material.004"]}
        position={[32.05, 0.51, -65.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.32}
      />
    </group>
  )
}

useGLTF.preload("assets/scenes/map.glb")
