/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 radio.glb
*/

import React, { useState } from "react"
import { useGLTF } from "@react-three/drei"

export function Radio({ Materials, onClick, position, rotation }) {
  const [isHovered, setIsHovered] = useState(false)
  const { nodes, materials } = useGLTF("/assets/objects/radio/radio.glb")

  const selectedHoveredMaterial = isHovered ? Materials.selectedMaterial : Materials.outlineMaterial

  return (
    <group
      onPointerEnter={() => setIsHovered(true)}
      onPointerLeave={() => setIsHovered(false)}
      onClick={onClick}
      position={position}
      rotation={rotation}
      dispose={null}
    >
      <group scale={0.0003}>
        <group position={[31.46, 59.05, -3.09]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Antenna_Outline_0.geometry} material={selectedHoveredMaterial} />
          <mesh
            geometry={nodes.Antenna_Simpsons_Radio_0.geometry}
            material={materials.Simpsons_Radio}
          />
        </group>
        <group position={[0, 50.08, 0.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Handle_Simpsons_Radio_0_1.geometry}
            material={materials.Simpsons_Radio}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Radio_Simpsons_Radio_0_1.geometry}
            material={materials.Simpsons_Radio}
          />
        </group>
      </group>
    </group>
  )
}
