/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene_cercles.glb --transform
*/

import React, { useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { getMaterials } from "@/helpers/materials/Materials"

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/scenes/scene_cercles-transformed.glb')

  const [Materials, setMaterials] = useState(null)

  useEffect(() => {
    getMaterials(props.variant).then((result) => setMaterials(result))
  }, [])

  if (Materials === null) {
    return <group></group>
  }

  return (
    <group {...props} dispose={null}>
      <group position={[-10.25, 11.02, -237.63]} scale={[174.33, 43.66, 73.17]}>
        <mesh geometry={nodes.Plane004.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-20.01, 12.36, -129.87]} rotation={[0.43, 0, 0]} scale={[0.1, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Sphere_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-16.27, 12.27, -114.96]} rotation={[3.12, 1.11, -3.04]} scale={[0.43, 0.22, 0.39]}>
        <mesh geometry={nodes.Sphere001_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.84, 12.41, -130.07]} rotation={[-0.14, 0.71, 1.95]} scale={[0.06, 0.06, 0.11]}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.69, 10.67, -299.39]} rotation={[-Math.PI, 1.46, -Math.PI]} scale={[0.41, 0.41, 0.76]}>
        <mesh geometry={nodes.Cube057.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube057_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[13.07, 12.15, -194.58]} rotation={[-Math.PI, 0.99, -2.99]} scale={[0.42, 0.33, 0.48]}>
        <mesh geometry={nodes.Cube051.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube051_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-32.63, 12.2, -125.61]} rotation={[0.01, 0.02, 0.08]} scale={[0.34, 0.17, 0.31]}>
        <mesh geometry={nodes.Sphere003_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-15.6, 12.21, -114.96]} rotation={[-3.08, 1.15, -3.02]} scale={[0.13, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere004_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-12.41, 12.55, -151.27]} rotation={[-2.81, 1.46, 2.81]} scale={[0.43, 0.1, 0.19]}>
        <mesh geometry={nodes.Sphere005_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere005_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-12.69, 12.56, -150.46]} rotation={[-2.81, 1.46, 2.81]} scale={[0.21, 0.05, 0.13]}>
        <mesh geometry={nodes.Sphere006_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere006_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-11.97, 12.57, -151.18]} rotation={[-0.11, 0.94, 2.53]} scale={[0.06, 0.06, 0.11]}>
        <mesh geometry={nodes.Sphere007_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere007_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.28, 12.07, -170.05]} rotation={[0, 0, -Math.PI]} scale={[-174.33, -26.31, -79.77]}>
        <mesh geometry={nodes.Plane002.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane002_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-4.28, 12.18, -116.79]} rotation={[0.01, 0.02, 0.08]} scale={[0.25, 0.13, 0.22]}>
        <mesh geometry={nodes.Sphere009_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere009_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-8.06, 11.97, -109.84]} rotation={[0.14, -0.98, 0.18]} scale={[0.15, 0.15, 0.26]}>
        <mesh geometry={nodes.Sphere010_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere010_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-7.67, 11.98, -109.81]} rotation={[-0.18, -0.15, 1.78]} scale={[0.09, 0.09, 0.15]}>
        <mesh geometry={nodes.Sphere011_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere011_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-7.66, 12.79, -123.22]} rotation={[2.42, 1.45, -2.44]} scale={[0.27, 0.07, 0.17]}>
        <mesh geometry={nodes.Sphere011_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere011_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-7.42, 12.81, -123.64]} rotation={[2.73, 1.47, -2.74]} scale={[0.16, 0.04, 0.07]}>
        <mesh geometry={nodes.Sphere011_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere011_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-112.45, 7.52, -584.38]} rotation={[0.17, 0, 0]} scale={[806.75, 81.86, 137.18]}>
        <mesh geometry={nodes.Plane003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-50.37, 10.53, -184.56]} rotation={[3.11, 0.67, -3.1]} scale={0.43}>
        <mesh geometry={nodes.Cube091.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube091_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-27.27, 10.89, -306.67]} rotation={[-Math.PI, 0.78, -Math.PI]} scale={[1.23, 0.4, 1.19]}>
        <mesh geometry={nodes.Cube235.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube235_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.56, 11.6, -111.58]} rotation={[-Math.PI, 0.35, -Math.PI]} scale={[0.41, 0.4, 0.4]}>
        <mesh geometry={nodes.Cube182.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube182_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-38.77, 12.24, -151.3]} rotation={[-Math.PI, 0.81, -Math.PI]} scale={0.2}>
        <mesh geometry={nodes.Cube182.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube182_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-27.84, 11.9, -144.01]} rotation={[Math.PI, -0.6, Math.PI]} scale={0.2}>
        <mesh geometry={nodes.Cube182.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube182_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-27.84, 11.9, -144.01]} rotation={[Math.PI, -0.6, Math.PI]} scale={0.2}>
        <mesh geometry={nodes.Cube182.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube182_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22.03, 11.37, -178.22]} rotation={[0.01, -0.36, 0.01]} scale={0.2}>
        <mesh geometry={nodes.Cube182.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube182_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[12.66, 11.6, -140.85]} rotation={[0, -0.11, 0]} scale={0.2}>
        <mesh geometry={nodes.Cube182.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube182_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.61, 11.45, -107.59]} rotation={[-Math.PI, 1.02, -Math.PI]} scale={0.26}>
        <mesh geometry={nodes.Cube183.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube183_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-16.39, 11.67, -110.32]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={0.26}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-37.96, 12.04, -145.82]} rotation={[-Math.PI, 0.73, -Math.PI]} scale={[0.21, 0.2, 0.2]}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22.31, 12.01, -143.94]} rotation={[Math.PI, -0.68, Math.PI]} scale={[0.21, 0.2, 0.2]}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22.31, 12.01, -143.94]} rotation={[Math.PI, -0.68, Math.PI]} scale={[0.21, 0.2, 0.2]}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.15, 11.55, -182.79]} rotation={[0.01, -0.28, 0.01]} scale={[0.21, 0.2, 0.2]}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[8.49, 11.66, -144.49]} rotation={[0, -0.03, 0]} scale={[0.21, 0.2, 0.2]}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-9.82, 11.6, -170.05]} rotation={[0, 0, -Math.PI]} scale={[-174.33, -26.31, -73.17]}>
        <mesh geometry={nodes.Plane011.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane011_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-2.13, 11.84, -103.64]} rotation={[0.01, 0, -3.11]} scale={[-174.33, -26.31, -73.17]}>
        <mesh geometry={nodes.Plane013.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane013_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-48.48, 6.94, -953.65]} rotation={[0.33, 0.15, -0.04]} scale={[868.26, 108.45, 139.9]}>
        <mesh geometry={nodes.Plane005.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-15.76, 10.81, -100.37]} rotation={[0, 0.39, 0]} scale={0.55}>
        <mesh geometry={nodes.Cube184.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube184_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-12.57, 18.54, -100.08]} rotation={[0, 0.39, 0]} scale={0.34}>
        <mesh geometry={nodes.Cube304_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube304_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-18.1, 24.07, -96.34]} rotation={[0.16, 0.1, -0.25]} scale={0.4}>
        <mesh geometry={nodes.Cube305_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube305_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.34, 21.27, -99.29]} rotation={[0, 0.39, 0.18]} scale={[0.4, 0.4, 0.47]}>
        <mesh geometry={nodes.Cube306_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube306_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-13.32, 22.14, -99.94]} rotation={[0, 0.39, -0.08]} scale={[0.36, 0.4, 0.57]}>
        <mesh geometry={nodes.Cube307_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube307_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-15.26, 24.03, -98.52]} rotation={[0, 0.39, 0]} scale={[0.57, 0.4, 0.5]}>
        <mesh geometry={nodes.Cube308.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube308_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[13.88, 20.6, -194.22]} rotation={[Math.PI, -0.75, Math.PI]} scale={[0.87, 0.49, 0.75]}>
        <mesh geometry={nodes.Cube322.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube322_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[11.07, 12.65, -192.11]} rotation={[Math.PI, -0.75, Math.PI]} scale={0.7}>
        <mesh geometry={nodes.Cube323.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube323_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[11.06, 18.35, -191.36]} rotation={[Math.PI, -1.2, -3.03]} scale={[0.3, 0.29, 0.4]}>
        <mesh geometry={nodes.Cube324.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube324_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[8.77, 19.33, -191.54]} rotation={[0, -0.81, 0.11]} scale={[0.35, 0.29, 0.35]}>
        <mesh geometry={nodes.Cube325.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube325_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-348.57, 24.12, -661.23]} rotation={[0, -1.28, 0]} scale={[0.39, 0.33, 0.33]}>
        <mesh geometry={nodes.Cube053.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube053_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-397.8, 18.9, -649.82]} rotation={[0, -1.39, 0]} scale={0.63}>
        <mesh geometry={nodes.Cube329.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube329_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-14.59, 12.42, -178.5]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.99}>
        <mesh geometry={nodes.Circle007.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Circle007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-4.8, 12.16, -103.92]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.28}>
        <mesh geometry={nodes.Circle007.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Circle007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-18.54, 12.24, -113.19]} rotation={[0, -0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle005.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Circle005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-6.69, 12.48, -116.5]} rotation={[0, -0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle005.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Circle005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-30.17, 12.34, -304.23]} rotation={[-0.51, -0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle005.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Circle005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-17.76, 12.31, -117.25]} rotation={[-Math.PI, 0.21, -Math.PI]} scale={1.12}>
        <mesh geometry={nodes.Circle773.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle773_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh geometry={nodes.pCube2_Ext_4.geometry} material={materials.M_Gas_Pump_2} />
      <group position={[-20.74, 12.31, -149.96]} rotation={[0.03, 0, 0]} scale={0.95}>
        <mesh geometry={nodes.Circle543.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle543_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-45.76, 11.86, -186.54]} rotation={[0.38, 0, -0.02]} scale={0.95}>
        <mesh geometry={nodes.Circle104.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle104_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-56.18, 11.91, -185.21]} rotation={[0.23, 0.62, -0.04]} scale={0.95}>
        <mesh geometry={nodes.Circle107.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle107_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22.17, 12.27, -116.5]} rotation={[0.03, 0, 0]} scale={0.95}>
        <mesh geometry={nodes.Circle006.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-36.79, 12.27, -114.22]} rotation={[3.11, -0.36, 3.13]} scale={0.95}>
        <mesh geometry={nodes.Circle109.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle109_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.75, 12.02, -122.31]} rotation={[3.12, 0.06, 3.13]} scale={0.95}>
        <mesh geometry={nodes.Circle110.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle110_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-36.87, 11.95, -125.2]} rotation={[-2.96, 0.06, -3.14]} scale={0.95}>
        <mesh geometry={nodes.Circle114.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle114_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[1.35, 12.27, -136.1]} rotation={[-3.11, -0.22, 0.01]} scale={-0.95}>
        <mesh geometry={nodes.Circle771.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle771_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-4.49, 11.84, -101.98]} rotation={[-2.97, -0.22, 0.01]} scale={-0.86}>
        <mesh geometry={nodes.Circle136.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle136_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-0.96, 11.91, -104.12]} rotation={[0.11, 0.21, -3.13]} scale={-0.86}>
        <mesh geometry={nodes.Circle192.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle192_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-15.69, 11.56, -100.96]} rotation={[-3.12, 0.91, 0]} scale={-0.86}>
        <mesh geometry={nodes.Circle072.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle072_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[63.04, 5.42, -584.57]} rotation={[Math.PI / 2, 0, 2.48]} scale={0.01}>
        <mesh geometry={nodes.Mesh053.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh053_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-345.6, 5.5, -761.45]} rotation={[Math.PI / 2, 0, 2.98]} scale={[0.03, 0.04, 0.02]}>
        <mesh geometry={nodes.Mesh061.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh061_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.79, 17.57, -681.93]} rotation={[Math.PI / 2, 0, -2.59]} scale={[0.02, 0.03, 0.01]}>
        <mesh geometry={nodes.Mesh007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[242.39, 14.49, -698.54]} rotation={[-Math.PI / 2, 0, -2.59]} scale={[-0.02, -0.03, -0.01]}>
        <mesh geometry={nodes.Mesh007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-368.37, 2.9, -584.57]} rotation={[Math.PI / 2, 0, 1.38]} scale={0.01}>
        <mesh geometry={nodes.Mesh012.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-105.89, 16.25, -896.23]} rotation={[Math.PI / 2, 0, 3.13]} scale={[0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[120.23, 16.25, -896.23]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[-0.04, -0.02, -0.01]}>
        <mesh geometry={nodes.Mesh014.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-221.23, 18.22, -890.31]} rotation={[Math.PI / 2, 0, 1.96]} scale={[0.04, 0.03, 0.01]}>
        <mesh geometry={nodes.Mesh024.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh024_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[247.67, 14.2, -890.31]} rotation={[Math.PI / 2, 0, -0.03]} scale={[0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-571.23, 16.25, -888.24]} rotation={[Math.PI / 2, 0, 3.13]} scale={[0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh006.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[13.88, 20.6, -194.22]} rotation={[Math.PI, -0.75, Math.PI]} scale={[0.87, 0.49, 0.75]}>
        <mesh geometry={nodes.Cube351.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube351_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[8.77, 19.33, -191.54]} rotation={[0, -0.81, 0.11]} scale={[0.35, 0.29, 0.35]}>
        <mesh geometry={nodes.Cube352.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube352_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[8.77, 19.33, -191.54]} rotation={[0, -0.81, 0.11]} scale={[0.35, 0.29, 0.35]}>
        <mesh geometry={nodes.Cube352.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube352_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[8.77, 19.33, -191.54]} rotation={[0, -0.81, 0.11]} scale={[0.35, 0.29, 0.35]}>
        <mesh geometry={nodes.Cube352.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube352_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[8.77, 19.33, -191.54]} rotation={[0, -0.81, 0.11]} scale={[0.35, 0.29, 0.35]}>
        <mesh geometry={nodes.Cube352.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube352_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-1.38, 14.23, -106.52]} rotation={[1.58, 0.08, -0.33]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-13.79, 14.39, -106.77]} rotation={[1.58, 0.03, 0.42]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-16.36, 13.97, -107.94]} rotation={[1.59, 0.11, 0.71]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-20.67, 13.49, -111.67]} rotation={[Math.PI / 2, 0, 0.72]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-1.43, 14.42, -106.56]} rotation={[Math.PI / 2, 0, 2.8]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[1.27, 14.35, -107.6]} rotation={[Math.PI / 2, 0, -2.93]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[4.1, 14.43, -107.03]} rotation={[Math.PI / 2, 0, -2.1]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-1.55, 13.33, -201.65]} rotation={[Math.PI / 2, 0, -3.09]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[1.33, 13.33, -201.53]} rotation={[Math.PI / 2, 0, -3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[4.22, 13.33, -201.56]} rotation={[Math.PI / 2, 0, -3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[7.14, 13.33, -201.59]} rotation={[Math.PI / 2, 0, -3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[10.05, 13.33, -201.61]} rotation={[Math.PI / 2, 0, -3.11]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[12.99, 13.33, -201.58]} rotation={[Math.PI / 2, 0, -3.1]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[15.91, 13.33, -201.47]} rotation={[Math.PI / 2, 0, -3.1]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[18.84, 13.33, -201.35]} rotation={[Math.PI / 2, 0, -3.06]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[21.78, 13.33, -201.13]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[24.68, 13.33, -201.2]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[27.6, 13.33, -201.25]} rotation={[Math.PI / 2, 0, -3.1]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-4.54, 13.33, -201.57]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-7.52, 13.33, -201.52]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-10.5, 13.33, -201.46]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-13.52, 13.33, -201.45]} rotation={[Math.PI / 2, 0, -3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-16.49, 13.33, -201.43]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.5, 13.33, -201.39]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22.5, 13.33, -201.35]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.49, 13.33, -201.32]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-28.49, 13.33, -201.28]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-31.48, 13.33, -201.23]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-34.47, 13.33, -201.2]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-37.46, 13.33, -201.16]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-40.45, 13.33, -201.11]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-43.44, 13.33, -201.08]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.43, 13.33, -201.04]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-49.4, 13.33, -200.99]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-52.36, 13.33, -200.96]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-55.33, 13.33, -200.93]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-58.31, 13.33, -200.88]} rotation={[Math.PI / 2, 0, 3.14]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-61.31, 13.33, -200.81]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-64.31, 13.33, -200.73]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-67.31, 13.33, -200.66]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-70.31, 13.33, -200.59]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-73.28, 13.33, -200.53]} rotation={[Math.PI / 2, 0, 3.13]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-76.3, 13.33, -200.41]} rotation={[Math.PI / 2, 0, 3.11]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-79.27, 13.33, -200.18]} rotation={[Math.PI / 2, 0, 3.08]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-82.24, 13.33, -199.78]} rotation={[Math.PI / 2, 0, 3.02]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-85.2, 13.33, -199.36]} rotation={[Math.PI / 2, 0, 3.02]} scale={0.43}>
        <mesh geometry={nodes.Fence_Cylinder004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.66, 12.51, -110.83]} rotation={[1.4, -0.09, 0.6]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder005_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder005_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.31, 12.56, -113.87]} rotation={[0.73, 0.08, -0.05]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder007_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder007_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.57, 14.39, -114.1]} rotation={[Math.PI / 2, 0, 0.09]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder009_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder009_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-28.4, 14.39, -114.31]} rotation={[Math.PI / 2, 0, 0.09]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder010_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder010_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-31.23, 14.39, -114.51]} rotation={[Math.PI / 2, 0, 0.09]} scale={0.41}>
        <mesh geometry={nodes.Fence_Cylinder010_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Fence_Cylinder010_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-15.28, 18.03, -104.81]} rotation={[-3.06, -1.4, -3.07]} scale={0.01}>
        <mesh geometry={nodes.Mesh040.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh040_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-13.45, 12.84, -104.97]} rotation={[0.61, -1.14, -2.42]} scale={[-0.03, -0.77, -0.66]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-13.42, 12.85, -105.03]} rotation={[-2.53, 1.14, -0.72]} scale={0}>
        <mesh geometry={nodes.Mesh060.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh060_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-13.91, 13.65, -105.06]} rotation={[-0.01, -0.6, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh066.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh066_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh geometry={nodes.Curve.geometry} material={Materials.floorMaterial} position={[-3.62, 14.33, -124.01]} rotation={[1.25, 0, 0.69]} scale={1.35} />
      <group position={[-9.71, 12.01, -123.09]} rotation={[-3.02, 0.75, 2.9]} scale={[0.41, 0.64, 0.4]}>
        <mesh geometry={nodes.Cube210.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube210_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-8.98, 11.38, -115.14]} rotation={[-3.04, 0.02, 2.91]} scale={[0.47, 0.58, 0.4]}>
        <mesh geometry={nodes.Cube228.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube228_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-7.1, 11.98, -125.37]} rotation={[-3.04, 0.02, 2.91]} scale={[0.47, 0.58, 0.4]}>
        <mesh geometry={nodes.Cube302.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube302_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-6.36, 12.36, -112.57]} rotation={[-3.05, 1.04, 3.04]} scale={[0.28, 0.42, 0.3]}>
        <mesh geometry={nodes.Cube089.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube089_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-2.54, 12.36, -117.68]} rotation={[0, 1.15, 0]} scale={[0.29, 0.36, 0.25]}>
        <mesh geometry={nodes.Cube301.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube301_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-4.72, 11.89, -114.66]} rotation={[-Math.PI, 1.3, -Math.PI]} scale={0.26}>
        <mesh geometry={nodes.Cube185.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube185_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-1.87, 12.14, -121.06]} rotation={[-Math.PI, 1.38, -Math.PI]} scale={0.25}>
        <mesh geometry={nodes.Cube119.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube119_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-9.72, 12.6, -118.75]} rotation={[-1.16, 0.15, -1.22]} scale={[-0.28, -0.63, -0.21]}>
        <mesh geometry={nodes.Cube094.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube094_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-3.32, 12.23, -124.44]} rotation={[3.09, 0.98, -3.04]} scale={[0.29, 0.82, 0.26]}>
        <mesh geometry={nodes.Cube211.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube211_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-38.17, 12.41, -143.74]} rotation={[-3.09, 0.48, 3.1]} scale={[0.22, 0.33, 0.23]}>
        <mesh geometry={nodes.Cube310.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube310_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-44.85, 12.14, -149.33]} rotation={[-3.05, 0.19, 2.96]} scale={[0.32, 0.51, 0.32]}>
        <mesh geometry={nodes.Cube314.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube314_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-41, 11.64, -144.34]} rotation={[-3.03, -0.54, 2.98]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube316.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube316_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-44.07, 12.11, -151.96]} rotation={[-3.03, -0.54, 2.98]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube318.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube318_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-37.78, 12.41, -148.76]} rotation={[-Math.PI, 1.43, -Math.PI]} scale={[0.23, 0.28, 0.2]}>
        <mesh geometry={nodes.Cube317.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube317_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-43.96, 12.38, -145.91]} rotation={[Math.PI, 0.32, -2.99]} scale={[0.23, 0.5, 0.2]}>
        <mesh geometry={nodes.Cube311.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube311_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-41.17, 12.31, -152.93]} rotation={[3.11, 0.41, -3.07]} scale={[0.23, 0.65, 0.21]}>
        <mesh geometry={nodes.Cube315.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube315_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-20.28, 11.85, -143.42]} rotation={[-3.06, -0.93, -3.09]} scale={[0.22, 0.33, 0.23]}>
        <mesh geometry={nodes.Cube007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-20.28, 11.85, -143.42]} rotation={[-3.06, -0.93, -3.09]} scale={[0.22, 0.33, 0.23]}>
        <mesh geometry={nodes.Cube007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.87, 11.4, -184.76]} rotation={[-0.04, -0.03, -0.01]} scale={[0.22, 0.33, 0.23]}>
        <mesh geometry={nodes.Cube007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[7.29, 11.7, -146.2]} rotation={[-0.05, 0.23, -0.01]} scale={[0.22, 0.33, 0.23]}>
        <mesh geometry={nodes.Cube007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-26.85, 11.38, -137.7]} rotation={[-2.89, -1.21, -3.07]} scale={[0.32, 0.51, 0.32]}>
        <mesh geometry={nodes.Cube008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-26.85, 11.38, -137.7]} rotation={[-2.89, -1.21, -3.07]} scale={[0.32, 0.51, 0.32]}>
        <mesh geometry={nodes.Cube008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-17.42, 10.96, -182.64]} rotation={[-0.08, 0.26, -0.13]} scale={[0.32, 0.51, 0.32]}>
        <mesh geometry={nodes.Cube008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[16, 12.05, -146.3]} rotation={[-0.1, 0.52, -0.11]} scale={[0.32, 0.51, 0.32]}>
        <mesh geometry={nodes.Cube008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-21.32, 11.4, -140.71]} rotation={[-0.26, -1.17, -0.46]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube011.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube011_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-21.32, 11.4, -140.71]} rotation={[-0.26, -1.17, -0.46]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube011.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube011_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.05, 11.1, -185.45]} rotation={[-0.18, 0.99, -0.06]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube011.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube011_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[9.83, 11.8, -147.59]} rotation={[-0.31, 1.24, 0.06]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube011.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube011_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-29.32, 11.16, -138.87]} rotation={[-0.26, -1.17, -0.46]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube012.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-29.32, 11.16, -138.87]} rotation={[-0.26, -1.17, -0.46]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube012.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-16.97, 11.12, -179.94]} rotation={[-0.18, 0.99, -0.06]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube012.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[17.12, 11.59, -143.8]} rotation={[-0.31, 1.24, 0.06]} scale={[0.37, 0.46, 0.32]}>
        <mesh geometry={nodes.Cube012.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.18, 11.99, -144.58]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[0.23, 0.28, 0.2]}>
        <mesh geometry={nodes.Cube013.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube013_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.18, 11.99, -144.58]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[0.23, 0.28, 0.2]}>
        <mesh geometry={nodes.Cube013.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube013_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.03, 11.44, -180.07]} rotation={[0.02, -0.97, 0.01]} scale={[0.23, 0.28, 0.2]}>
        <mesh geometry={nodes.Cube013.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube013_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[10.26, 11.61, -142.14]} rotation={[0, -0.72, 0]} scale={[0.23, 0.28, 0.2]}>
        <mesh geometry={nodes.Cube013.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube013_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.33, 12.12, -138.04]} rotation={[Math.PI, -1.1, -2.99]} scale={[0.23, 0.5, 0.2]}>
        <mesh geometry={nodes.Cube016.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube016_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.33, 12.12, -138.04]} rotation={[Math.PI, -1.1, -2.99]} scale={[0.23, 0.5, 0.2]}>
        <mesh geometry={nodes.Cube016.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube016_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.71, 11.35, -185.32]} rotation={[0.01, 0.13, 0.16]} scale={[0.23, 0.5, 0.2]}>
        <mesh geometry={nodes.Cube016.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube016_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[13.09, 12.43, -148.32]} rotation={[0, 0.39, 0.15]} scale={[0.23, 0.5, 0.2]}>
        <mesh geometry={nodes.Cube016.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube016_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-29.83, 12, -141.9]} rotation={[3.09, -1, -3.13]} scale={[0.23, 0.65, 0.21]}>
        <mesh geometry={nodes.Cube039.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube039_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-29.83, 12, -141.9]} rotation={[3.09, -1, -3.13]} scale={[0.23, 0.65, 0.21]}>
        <mesh geometry={nodes.Cube039.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube039_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-19.16, 11.51, -177.78]} rotation={[0.04, 0.04, 0.06]} scale={[0.23, 0.65, 0.21]}>
        <mesh geometry={nodes.Cube039.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube039_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[15.55, 11.82, -141.17]} rotation={[0.03, 0.3, 0.05]} scale={[0.23, 0.65, 0.21]}>
        <mesh geometry={nodes.Cube039.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube039_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh geometry={nodes.terrain292.geometry} material={Materials.floorMaterial} position={[-12.57, 12.02, -105.2]} rotation={[-0.04, -0.93, -0.08]} scale={0} />
      <mesh geometry={nodes.terrain011.geometry} material={Materials.floorMaterial} position={[-4.57, 12.23, -111.21]} rotation={[-3.1, 0.93, 3.06]} scale={0} />
      <mesh geometry={nodes.Vegetal_texture014.geometry} material={materials['Material.011']} position={[-8.14, 12.26, -101.92]} rotation={[-1.57, 0, -3.01]} scale={[0.91, 0.31, 0.32]} />
      <mesh geometry={nodes.Vegetal_texture001.geometry} material={materials['Material.011']} position={[-12.42, 12.62, -111.89]} rotation={[-1.57, 0, -3.01]} scale={[0.91, 0.31, 0.32]} />
      <mesh geometry={nodes.Vegetal_texture002.geometry} material={materials['Material.011']} position={[-12.1, 11.93, -98.74]} rotation={[-1.57, 0, -3.01]} scale={[0.91, 0.31, 0.32]} />
      <mesh geometry={nodes.group_0_ID4.geometry} material={Materials.floorMaterial} position={[-120.98, 10.35, -248.08]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4001.geometry} material={Materials.floorMaterial} position={[-120.98, 14.6, -248.08]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4002.geometry} material={Materials.floorMaterial} position={[-297.66, 16.71, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4003.geometry} material={Materials.floorMaterial} position={[-315.1, 16.71, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4004.geometry} material={Materials.floorMaterial} position={[-332.56, 16.71, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4005.geometry} material={Materials.floorMaterial} position={[-349.99, 16.71, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4006.geometry} material={Materials.floorMaterial} position={[-349.99, 21.19, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4007.geometry} material={Materials.floorMaterial} position={[-349.99, 25.7, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4008.geometry} material={Materials.floorMaterial} position={[-315.1, 21.19, -642.66]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
    </group>
  )
}

useGLTF.preload('/assets/scenes/scene_cercles-transformed.glb')
