/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cities_sign.glb --transform
*/

import React, { useState, useEffect } from "react"
import { useGLTF, useTexture } from "@react-three/drei"
import { getMaterials } from "@/helpers/materials/Materials"
import { MeshToonMaterial } from "three"

export function Model({ position, rotation, pubHovered, setPubHovered, onPubClick }) {
  const { nodes, materials } = useGLTF("assets/objects/signs/cities_sign.glb")
  const citiesSignTexture = useTexture("assets/images/cities_sign.jpg")
  citiesSignTexture.flipY = false
  const [Materials, setMaterials] = useState(null)

  useEffect(() => {
    getMaterials().then((result) => setMaterials(result))
  }, [])

  if (Materials === null) {
    return <group></group>
  }
  return (
    <group position={position} rotation={rotation} dispose={null}>
      <group position={[-0.01, 2.75, -0.16]} rotation={[0, 0, -0.01]} scale={[-0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.fenceMaterial} />
        <mesh
          geometry={nodes.Mesh027_1.geometry}
          material={pubHovered ? Materials.selectedMaterial : Materials.outlineMaterial}
        />
      </group>
      <group position={[-0.02, 1.61, -0.16]} rotation={[0, 0, -0.01]} scale={[-0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.fenceMaterial} />
        <mesh
          geometry={nodes.Mesh027_1.geometry}
          material={pubHovered ? Materials.selectedMaterial : Materials.outlineMaterial}
        />
      </group>
      <group position={[-0.02, 0.85, -0.25]} rotation={[0, 0, -0.01]} scale={[-0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh014.geometry} material={Materials.fenceMaterial} />
        <mesh
          geometry={nodes.Mesh014_1.geometry}
          material={pubHovered ? Materials.selectedMaterial : Materials.outlineMaterial}
        />
      </group>
      <group position={[0.13, 2.22, 0.03]} rotation={[0, 0, -0.01]} scale={[0.09, 1.32, -1.98]}>
        <mesh geometry={nodes.Cube184.geometry} material={Materials.fenceMaterial} />
        <mesh
          geometry={nodes.Cube184_1.geometry}
          material={pubHovered ? Materials.selectedMaterial : Materials.outlineMaterial}
        />
      </group>
      <group
        onClick={onPubClick}
        onPointerEnter={() => setPubHovered(true)}
        onPointerLeave={() => setPubHovered(false)}
        position={[0.13, 2.22, 0.03]}
        rotation={[0, 0, -0.01]}
        scale={[0.09, 1.32, -1.98]}
      >
        <mesh
          geometry={nodes.Cube185.geometry}
          material={new MeshToonMaterial({ map: citiesSignTexture })}
        />
        <mesh
          geometry={nodes.Cube185_1.geometry}
          material={pubHovered ? Materials.selectedMaterial : Materials.outlineMaterial}
        />
      </group>
    </group>
  )
}

useGLTF.preload("assets/objects/signs/cities_sign.glb")
