/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 welcome_sign.glb --transform
*/

import React, { useState, useEffect } from "react"
import { useGLTF, useTexture } from "@react-three/drei"
import { getMaterials } from "@/helpers/materials/Materials"
import { MeshBasicMaterial } from "three"

export const Model = ({ position, rotation, onMapClick, onPubClick }) => {
  const { nodes, materials } = useGLTF("assets/objects/signs/welcome_sign.glb")
  const mapTexture = useTexture("assets/images/nyalaande_map.png")
  mapTexture.flipY = false
  const truckTexture = useTexture("assets/images/truck.jpg")
  truckTexture.flipY = false
  const [Materials, setMaterials] = useState(null)

  useEffect(() => {
    getMaterials().then((result) => setMaterials(result))
  }, [])

  if (Materials === null) {
    return <group></group>
  }
  return (
    <group position={position} rotation={rotation} dispose={null}>
      <group position={[3.69, 6.6, 2.46]} rotation={[0.02, -0.13, 0]} scale={[-0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[3.68, 5.46, 2.44]} rotation={[0.02, -0.13, 0]} scale={[-0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[1.2, 8.45, -5.32]}
        rotation={[-0.04, -0.98, -0.05]}
        scale={[-0.01, 0.01, 0.01]}
      >
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[1.14, 6.41, -5.32]}
        rotation={[-0.04, -0.98, -0.05]}
        scale={[-0.01, 0.01, 0.01]}
      >
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[3.69, 4.71, 2.33]} rotation={[0.02, -0.13, 0]} scale={[-0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh014.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[3.8, 6.07, 2.66]} rotation={[0.02, -0.14, 0]} scale={[0.09, 1.32, -1.98]}>
        <mesh geometry={nodes.Cube184.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube184_1.geometry} material={materials["Material.015"]} />
      </group>
      <group
        position={[1.14, 7.06, -5.08]}
        rotation={[-0.04, -0.98, -0.05]}
        scale={[0.12, 2.55, -1.6]}
      >
        <mesh geometry={nodes.Cube196.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube196_1.geometry} material={materials["Material.010"]} />
      </group>
      <group onClick={onPubClick} position={[3.8, 6.07, 2.66]} rotation={[0.02, -0.14, 0]} scale={[0.09, 1.32, -1.98]}>
        <mesh geometry={nodes.Cube185.geometry} material={new MeshBasicMaterial({ map: truckTexture })} />
        <mesh geometry={nodes.Cube185_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        onClick={onMapClick}
        position={[1.14, 7.06, -5.08]}
        rotation={[-0.04, -0.98, -0.05]}
        scale={[0.12, 2.55, -1.6]}
      >
        <mesh geometry={nodes.Cube197.geometry} material={new MeshBasicMaterial({ map: mapTexture })} />
        <mesh geometry={nodes.Cube197_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[1.15, 4.41, -5.36]}
        rotation={[-0.04, -0.98, -0.05]}
        scale={[-0.01, 0.01, 0.01]}
      >
        <mesh geometry={nodes.Mesh041.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh041_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[0.84, 9.37, -4.15]} rotation={[3.1, 0.98, 1.62]} scale={[0.03, 0.23, 0.03]}>
        <mesh geometry={nodes.Cube194.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube194_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[2.2, 9.34, -5.06]} rotation={[3.1, 0.98, 1.62]} scale={[0.03, 0.23, 0.03]}>
        <mesh geometry={nodes.Cube194.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube194_1.geometry} material={Materials.outlineMaterial} />
      </group>
    </group>
  )
}

useGLTF.preload("assets/objects/signs/welcome_sign.glb")
