/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.10 keur_gnialo.glb --transform
*/

import React from "react"
import { useTexture } from "@react-three/drei"
import { MeshBasicMaterial } from "three"

export function Model({ nodes, Materials, materials, position, rotation }) {
  const pubTexture = useTexture("/assets/images/keurgnialo_pub.jpg")
  pubTexture.flipY = false

  return (
    <group position={position} rotation={rotation} dispose={null}>
      <group
        position={[45.49, 13.08, 24.71]}
        rotation={[3.02, 1.55, -3.02]}
        scale={[0.01, 0.01, -0.01]}
      >
        <mesh geometry={nodes.pCube2_Ext_4.geometry} material={materials.M_Gas_Pump_2} />
        <mesh geometry={nodes.pCylinder6.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.SmartCombine_100.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_105.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_107.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_111.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_115.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_34.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_61.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_76.geometry} material={Materials.metalMaterials.main} />
        <mesh geometry={nodes.SmartCombine_92.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_93.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_97.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.SmartCombine_99.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_45.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_54.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_58.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartExtract_42.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartSeparate_47.geometry} material={Materials.metalMaterials.main} />
        <mesh geometry={nodes.SmartSeparate_70.geometry} material={Materials.metalMaterials.main} />
        <mesh geometry={nodes.SmartSeparate_71.geometry} material={Materials.metalMaterials.main} />
        <mesh geometry={nodes.SmartSeparate_72.geometry} material={Materials.metalMaterials.main} />
        <mesh geometry={nodes.SmartSeparate_75.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_87.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.Mesh040.geometry} material={Materials.gasPumpMaterials.white} />
        <mesh geometry={nodes.Mesh040_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh042.geometry} material={Materials.gasPumpMaterials.orange} />
        <mesh geometry={nodes.Mesh042_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh012.geometry} material={Materials.gasPumpMaterials.white} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh049.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh049_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh046.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh046_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh047.geometry} material={Materials.metalMaterials.main} />
        <mesh geometry={nodes.Mesh047_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh043.geometry} material={Materials.gasPumpMaterials.orange} />
        <mesh geometry={nodes.Mesh043_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh044.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[45.27, 13.08, 14.97]}
        rotation={[3.02, 1.55, -3.02]}
        scale={[0.01, 0.01, -0.01]}
      >
        <mesh
          geometry={nodes.pCube2_Ext_4001.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh geometry={nodes.pCylinder6001.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.SmartCombine_100001.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_105001.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_107001.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_111001.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_115001.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_34001.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_61001.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_76001.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartCombine_92001.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_93001.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_97001.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.SmartCombine_99001.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_45001.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_54001.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_58001.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartExtract_42001.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_47001.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_70001.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_71001.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_72001.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartSeparate_75001.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_87001.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_109001.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_90001.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_96001.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartDuplicate_55001.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartExtract_26001.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.SmartExtract_43001.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh geometry={nodes.Mesh049.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh049_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh044.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[32.68, 13.08, 15.29]}
        rotation={[3.02, 1.55, -3.02]}
        scale={[0.01, 0.01, -0.01]}
      >
        <mesh
          geometry={nodes.pCube2_Ext_4002.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh geometry={nodes.pCylinder6002.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.SmartCombine_100002.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_105002.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_107002.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_111002.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_115002.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_34002.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_61002.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_76002.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartCombine_92002.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_93002.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_97002.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.SmartCombine_99002.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_45002.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_54002.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_58002.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartExtract_42002.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_47002.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_70002.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_71002.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_72002.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartSeparate_75002.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_87002.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_109002.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_90002.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartDuplicate_55002.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartExtract_26002.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartExtract_43002.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_96002.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.Mesh049.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh049_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh044.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[32.93, 13.08, 25.05]}
        rotation={[3.02, 1.55, -3.02]}
        scale={[0.01, 0.01, -0.01]}
      >
        <mesh
          geometry={nodes.pCube2_Ext_4003.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh geometry={nodes.pCylinder6003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.SmartCombine_100003.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_105003.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_107003.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_111003.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_115003.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_34003.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_61003.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_76003.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartCombine_92003.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_93003.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_97003.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.SmartCombine_99003.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_45003.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_54003.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_58003.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartExtract_42003.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_47003.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_70003.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_71003.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_72003.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartSeparate_75003.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_87003.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_109003.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_90003.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartDuplicate_55003.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartExtract_26003.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartExtract_43003.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_96003.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.Mesh049.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh049_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh044.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[19.91, 13.08, 25.36]}
        rotation={[3.02, 1.55, -3.02]}
        scale={[0.01, 0.01, -0.01]}
      >
        <mesh
          geometry={nodes.pCube2_Ext_4004.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh geometry={nodes.pCylinder6004.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.SmartCombine_100004.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_105004.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_107004.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_111004.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_115004.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_34004.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_61004.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_76004.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartCombine_92004.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_93004.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_97004.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.SmartCombine_99004.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_45004.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_54004.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_58004.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartExtract_42004.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_47004.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_70004.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_71004.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_72004.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartSeparate_75004.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_87004.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_109004.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_90004.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartDuplicate_55004.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartExtract_26004.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartExtract_43004.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_96004.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.Mesh049.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh049_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh044.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[19.68, 13.08, 15.6]}
        rotation={[3.02, 1.55, -3.02]}
        scale={[0.01, 0.01, -0.01]}
      >
        <mesh
          geometry={nodes.pCube2_Ext_4005.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh geometry={nodes.pCylinder6005.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.SmartCombine_100005.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_105005.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh geometry={nodes.SmartCombine_107005.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_111005.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_115005.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_34005.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_61005.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_76005.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartCombine_92005.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartCombine_93005.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_97005.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.SmartCombine_99005.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_45005.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_54005.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartDuplicate_58005.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.SmartExtract_42005.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_47005.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_70005.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_71005.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh
          geometry={nodes.SmartSeparate_72005.geometry}
          material={Materials.metalMaterials.main}
        />
        <mesh geometry={nodes.SmartSeparate_75005.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.SmartSeparate_87005.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartCombine_109005.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartCombine_90005.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartDuplicate_55005.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.SmartExtract_26005.geometry}
          material={Materials.gasPumpMaterials.ledScreen}
        />
        <mesh
          geometry={nodes.SmartExtract_43005.geometry}
          material={Materials.gasPumpMaterials.orange}
        />
        <mesh
          geometry={nodes.SmartCombine_96005.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh geometry={nodes.Mesh049.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh049_1.geometry} material={Materials.outlineMaterial} />
        <mesh geometry={nodes.Mesh044.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0135.geometry}
        material={Materials.floorMaterial}
        position={[28.15, 13.04, 26.42]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <group
        position={[44.64, 12.74, -0.18]}
        rotation={[-2.13, -0.03, 0.89]}
        scale={[0.4, 0.4, 0.46]}
      >
        <mesh geometry={nodes.Cube119.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube119_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-12.92, 12.47, -13.65]} rotation={[-Math.PI, 1.52, -Math.PI]} scale={0.35}>
        <mesh geometry={nodes.Cube004_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-4.7, 12.98, -14.3]}
        rotation={[-0.15, 1.03, 0.16]}
        scale={[0.34, 0.17, 0.31]}
      >
        <mesh geometry={nodes.Sphere003_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[46.29, 12.78, -12.75]} rotation={[-0.08, -0.94, 0.02]} scale={0}>
        <mesh geometry={nodes.Mesh296.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh296_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[2.66, 13, -3.41]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[160.54, 5.5, -67.38]}
      >
        <mesh geometry={nodes.Plane002.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane002_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Route.geometry}
        material={Materials.roadMaterials.main}
        position={[-8.35, 11.42, -6.34]}
        rotation={[-Math.PI, 1, -Math.PI]}
        scale={[4.17, 2, 5.43]}
      />
      <group position={[-63.54, 20.67, 5.38]} rotation={[-0.03, -0.33, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh002.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[0.63, 14.07, 0.74]}
        rotation={[-Math.PI, 1.55, -Math.PI]}
        scale={[-0.02, 0.02, 0.02]}
      >
        <mesh geometry={nodes.Mesh005.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[17.8, 13.01, -4.12]} rotation={[-Math.PI, 1.27, -Math.PI]} scale={2.49}>
        <mesh geometry={nodes.Circle006.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[37.85, 13.01, -13.79]} rotation={[-Math.PI, -0.59, -Math.PI]} scale={2.49}>
        <mesh geometry={nodes.Circle006.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-10.52, 13, -13.47]} rotation={[-Math.PI, -0.59, -Math.PI]} scale={2.21}>
        <mesh geometry={nodes.Circle006.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[56.1, 14.12, 0.06]}
        rotation={[-Math.PI, 1.55, -Math.PI]}
        scale={[-0.02, 0.02, 0.02]}
      >
        <mesh geometry={nodes.Mesh001.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[49.51, 18.31, -0.56]} rotation={[2.73, 1.57, -2.73]} scale={0.01}>
        <mesh geometry={nodes.Mesh004.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[16.33, 18.31, 0.05]} rotation={[2.73, 1.57, -2.73]} scale={0.01}>
        <mesh geometry={nodes.Mesh004.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-85.5, 18.77, -0.27]} rotation={[0.01, -1.31, 0.01]} scale={0.01}>
        <mesh geometry={nodes.Mesh004.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-29.03, 17.87, 29.17]} rotation={[0, -0.15, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh004.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Route_2002.geometry}
        material={Materials.floorMaterial}
        position={[-22.43, 11.58, 14.15]}
        rotation={[-Math.PI, -0.45, -Math.PI]}
        scale={[4.17, 2, 5.43]}
      />
      <mesh
        geometry={nodes.Sand_1002.geometry}
        material={Materials.floorMaterial}
        position={[7.67, 12.44, 12.61]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[160.54, 33.02, -67.38]}
      />
      <mesh
        geometry={nodes.Sand_1003.geometry}
        material={Materials.floorMaterial}
        position={[-41.58, 12.44, -142.07]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[224.15, 46.1, -94.08]}
      />
      <group position={[-29.8, 20.36, 15.19]} rotation={[-0.82, -1.54, -0.81]} scale={0.01}>
        <mesh geometry={nodes.Mesh232.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh232_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-38.99, 17.41, 8.75]}
        rotation={[-1.57, 0, 2.66]}
        scale={[0.19, 0.21, -0.21]}
      >
        <mesh geometry={nodes.Mesh273.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh273_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-44.17, 22.04, 18.56]}
        rotation={[1.57, 0, -1.09]}
        scale={[0.2, -0.21, -0.21]}
      >
        <mesh geometry={nodes.Mesh279.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh279_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-79.85, 22.15, -13.46]}
        rotation={[1.58, 0, 0.18]}
        scale={[0.2, -0.21, -0.21]}
      >
        <mesh geometry={nodes.Mesh279.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh279_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-41.59, 18.4, 14.34]} rotation={[0, 1.09, 0]} scale={[5.38, 1.89, 9.46]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube001_1.geometry} material={Materials.houseMaterials.backwall} />
        <mesh geometry={nodes.Cube001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-41.86, 21.17, 14.2]} rotation={[0, 1.09, 0]} scale={[5.49, 0.9, 9.46]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube002_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-75, 21.29, -12.56]} rotation={[0, -0.18, 0]} scale={[5.49, 0.9, 9.46]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube002_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={Materials.houseMaterials.backwall}
        position={[-41.81, 17.09, 14.11]}
        rotation={[0, 1.09, 0]}
        scale={[0.24, 4.24, 8.33]}
      />
      <group
        position={[-50.09, 22.04, 27.45]}
        rotation={[1.57, 0, -0.94]}
        scale={[0.2, -0.21, -0.21]}
      >
        <mesh geometry={nodes.Mesh003.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-49.31, 17.41, 28.02]}
        rotation={[-1.57, 0, 0.94]}
        scale={[0.19, 0.21, -0.21]}
      >
        <mesh geometry={nodes.Mesh007.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Box001006.geometry}
        material={Materials.houseMaterials.main}
        position={[-52.17, 22.05, 27.28]}
        rotation={[1.57, 0, 0.63]}
        scale={[0.2, -0.21, -0.21]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={Materials.houseMaterials.wall}
        position={[-49.8, 18.42, 26.41]}
        rotation={[0, -0.63, 0]}
        scale={[5.38, 1.89, 9.46]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={Materials.houseMaterials.wall}
        position={[-49.85, 21.17, 27.63]}
        rotation={[0, -0.63, 0]}
        scale={[5.49, 0.9, 9.46]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={Materials.stoneMaterial}
        position={[-52.85, 17.25, 25.47]}
        rotation={[0, -0.63, 0]}
        scale={[5.49, 4.51, 9.46]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={Materials.houseMaterials.wall}
        position={[-50.27, 14.66, 26.91]}
        rotation={[0, -0.63, 0]}
        scale={[5.38, 1.82, 8.57]}
      />
      <group position={[-75.05, 18.52, -12.27]} rotation={[0, -0.18, 0]} scale={[5.38, 1.89, 9.46]}>
        <mesh geometry={nodes.Cube029_1.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube029_1.geometry} material={Materials.houseMaterials.backwall} />
        <mesh geometry={nodes.Cube029_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-75, 14.81, -12.56]} rotation={[0, -0.18, 0]} scale={[5.38, 1.82, 8.57]}>
        <mesh geometry={nodes.Cube031.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube031.geometry} material={Materials.houseMaterials.backwall} />
        <mesh geometry={nodes.Cube031_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Cube021.geometry}
        material={Materials.houseMaterials.backwall}
        position={[-75.63, 17.62, -12.09]}
        rotation={[0, -0.15, 0]}
        scale={[0.24, 4.24, 8.33]}
      />
      <group
        position={[25.4, 11.96, 25.58]}
        rotation={[-Math.PI, 1.55, -Math.PI]}
        scale={[23.33, -1.24, 39.34]}
      >
        <mesh geometry={nodes.Cube_1.geometry} material={Materials.concreteMaterial} />
        <mesh geometry={nodes.Cube_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[33.37, 23.67, 19.62]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0001_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group
        position={[21.58, 21.1, 37.91]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={[1.63, 1.63, 3.29]}
      >
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0002_1.geometry}
          material={Materials.gasPumpMaterials.wall}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0002_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group
        position={[32.96, 21.1, 37.63]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={[1.63, 1.63, 3.29]}
      >
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0003_1.geometry}
          material={Materials.gasPumpMaterials.wall}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0003_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group
        position={[44.33, 21.1, 37.35]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={[1.63, 1.63, 3.29]}
      >
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0004_1.geometry}
          material={Materials.gasPumpMaterials.wall}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0004_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-2.89, 15.99, 11.39]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0039_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0039_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-2.93, 14.48, 9.98]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0041_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0041_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-1.89, 14.83, 11.97]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0043_1.geometry}
          material={Materials.gasPumpMaterials.white}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0043_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.23, 17.22, 16.26]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0047_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0047_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.22, 21.41, 14.5]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0049_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0049_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.3, 14.52, 17.58]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0055_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0055_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.31, 14.05, 18.13]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0056_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0056_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.47, 17.22, 26.01]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0061_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0061_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.46, 21.41, 24.25]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0063_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0063_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.55, 14.05, 27.88]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0070_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0070_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0075.geometry}
        material={Materials.fenceMaterial}
        position={[32.65, 17.22, 16.57]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0077.geometry}
        material={Materials.gasPumpMaterials.green}
        position={[32.64, 21.41, 14.81]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <group position={[32.58, 15.03, 12.31]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.62, 15.03, 12.65]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.85, 15.03, 22.39]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[32.85, 15.03, 22.06]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.41, 15.03, 21.75]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[45.19, 15.03, 12]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_1.geometry}
          material={Materials.concreteMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0080_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0086.geometry}
        material={Materials.concreteMaterial}
        position={[32.67, 13.37, 15.3]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0088.geometry}
        material={Materials.concreteMaterial}
        position={[32.72, 13.46, 17.99]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <group position={[32.89, 17.22, 26.32]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0089_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0089_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[32.88, 21.41, 24.56]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0091_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0091_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.65, 17.22, 16.88]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0104_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0104_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.64, 21.41, 15.13]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0106_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0106_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.89, 17.22, 26.63]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0117_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0117_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.88, 21.41, 24.87]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0119_1.geometry}
          material={Materials.gasPumpMaterials.green}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0119_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0131.geometry}
        material={Materials.gasPumpMaterials.green}
        position={[32.62, 24.43, 24.56]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <group position={[-2.93, 13.24, 13.45]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.63}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0132_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0132_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0133.geometry}
        material={Materials.gasPumpMaterials.wall}
        position={[32.62, 22.8, 24.56]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0134.geometry}
        material={Materials.gasPumpMaterials.green}
        position={[32.99, 23.64, 39.61]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.63}
      />
      <group position={[29.15, 14.15, 30.76]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.18}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0137_1.geometry}
          material={Materials.gasPumpMaterials.wall}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0137_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[19.67, 13.37, 13.9]} rotation={[Math.PI / 2, 0, -1.56]} scale={2.77}>
        <mesh geometry={nodes.bin001_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.bin001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[19.97, 13.37, 23.53]} rotation={[Math.PI / 2, 0, -1.56]} scale={2.77}>
        <mesh geometry={nodes.bin001_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.bin001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[33.08, 13.37, 23.08]} rotation={[Math.PI / 2, 0, -1.56]} scale={2.77}>
        <mesh geometry={nodes.bin001_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.bin001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[45.48, 13.37, 23.06]} rotation={[Math.PI / 2, 0, -1.56]} scale={2.77}>
        <mesh geometry={nodes.bin001_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.bin001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[32.67, 13.37, 13.21]} rotation={[Math.PI / 2, 0, -1.61]} scale={2.77}>
        <mesh geometry={nodes.bin001_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.bin001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[45.24, 13.37, 13.11]} rotation={[Math.PI / 2, 0, -1.61]} scale={2.77}>
        <mesh geometry={nodes.bin001_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.bin001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[32.76, 13.89, 14.11]} rotation={[-Math.PI, 0.45, -Math.PI]} scale={2.63}>
        <mesh geometry={nodes.Cube020_1.geometry} material={Materials.gasPumpMaterials.jerrycan} />
        <mesh geometry={nodes.Cube020_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[4.08, 14.05, 31.29]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.18}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0012_1.geometry}
          material={Materials.gasPumpMaterials.wall}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0012_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-38.66, 19.16, 36.12]} rotation={[0, 0.03, 0]} scale={[6.12, 2.44, 8.09]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube005_1.geometry} material={Materials.houseMaterials.backwall} />
        <mesh geometry={nodes.Cube005_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-38.47, 14.68, 35.92]} rotation={[0, 0.03, 0]} scale={[6, 2.03, 8.01]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={Materials.houseMaterials.wall} />
        <mesh geometry={nodes.Cube006_1.geometry} material={Materials.houseMaterials.backwall} />
        <mesh geometry={nodes.Cube006_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-31.02, 17.48, 35.9]} rotation={[-Math.PI, 1.54, -Math.PI]} scale={0.05}>
        <mesh geometry={nodes.Mesh028.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh028_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-36.49, 22.03, 35.98]} rotation={[0, 0.03, 0]} scale={[-0.03, 0.03, -0.03]}>
        <mesh geometry={nodes.Mesh056.geometry} material={Materials.houseMaterials.main} />
        <mesh geometry={nodes.Mesh056_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-32.84, 12.84, 24.19]} rotation={[Math.PI / 2, 0, -1.87]} scale={0.75}>
        <mesh geometry={nodes.Cube007_1.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube007_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[6.48, 13.03, 17.68]} rotation={[Math.PI / 2, 0, -1.59]} scale={0.75}>
        <mesh geometry={nodes.Cube019_1.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube019_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[6.79, 12.06, 31.84]} rotation={[Math.PI / 2, 0, -1.59]} scale={0.75}>
        <mesh geometry={nodes.Cube022_1.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube022_2.geometry} material={Materials.floorMaterial} />
      </group>
      <mesh
        geometry={nodes.Rusty_can.geometry}
        material={Materials.metalMaterials.rusty}
        position={[51.53, 14.21, 14.36]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={2.39}
      />
      <mesh
        geometry={nodes.can.geometry}
        material={Materials.metalMaterials.rusty}
        position={[51.51, 14.21, 13.1]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={2.39}
      />
      <group position={[51.45, 14.21, 11.86]} rotation={[-Math.PI, 1.27, -Math.PI]} scale={2.39}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={Materials.metalMaterials.rusty} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[51.49, 16.26, 13.72]} rotation={[0, -1.21, 0]} scale={2.39}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={Materials.metalMaterials.rusty} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[51.45, 16.23, 12.4]} rotation={[-1.45, -1.42, -1.48]} scale={2.39}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={Materials.metalMaterials.rusty} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[6.07, 13.56, 16.04]} rotation={[-2.69, 0.1, -3.07]} scale={1.92}>
        <mesh geometry={nodes.Cube023_1.geometry} material={Materials.gasPumpMaterials.jerrycan} />
        <mesh geometry={nodes.Cube023_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Curve007.geometry}
        material={Materials.gasPumpMaterials.green}
        position={[32.26, 17.81, 32.36]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={[2.98, 10.58, 3.08]}
      />
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0032.geometry}
        material={Materials.fenceMaterial}
        position={[35.56, 14.7, 31.83]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.21}
      />
      <group
        position={[32.26, 16.32, 38.23]}
        rotation={[-Math.PI, 1.55, -Math.PI]}
        scale={[-6.29, -3.16, -13.16]}
      >
        <mesh geometry={nodes.Cube185.geometry} material={Materials.gasPumpMaterials.wall} />
        <mesh geometry={nodes.Cube185_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-10.48, 18.9, -16.23]}
        rotation={[-Math.PI, -1.08, -3.03]}
        scale={[0.27, 0.23, 0.28]}
      >
        <mesh geometry={nodes.Cube325.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube325_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-9.96, 18.33, -14.05]}
        rotation={[-Math.PI, 0.05, -3.03]}
        scale={[0.23, 0.23, 0.24]}
      >
        <mesh geometry={nodes.Cube324.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube324_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-9.48, 13.63, -14.66]} rotation={[-Math.PI, 0.5, -Math.PI]} scale={0.55}>
        <mesh geometry={nodes.Cube323.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube323_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-7.21, 19.9, -13.08]}
        rotation={[-Math.PI, 0.5, -Math.PI]}
        scale={[0.69, 0.39, 0.59]}
      >
        <mesh geometry={nodes.Cube322.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube322_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[58.72, 18.72, -17.18]}
        rotation={[-Math.PI, -1.15, -3.03]}
        scale={[0.35, 0.29, 0.35]}
      >
        <mesh geometry={nodes.Cube013_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube013_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[59.57, 18, -14.46]}
        rotation={[-Math.PI, 0.65, -3.03]}
        scale={[0.3, 0.29, 0.31]}
      >
        <mesh geometry={nodes.Cube014_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube014_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[60.12, 12.03, -15.27]} rotation={[-Math.PI, 0.43, -Math.PI]} scale={0.7}>
        <mesh geometry={nodes.Cube015_1.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube015_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[63.14, 19.74, -13.79]}
        rotation={[-Math.PI, 0.43, -Math.PI]}
        scale={[0.72, 0.4, 0.61]}
      >
        <mesh geometry={nodes.Cube026_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube026_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={Materials.fenceMaterial}
        position={[-61.86, 14.85, -3.77]}
        rotation={[-Math.PI, 0.33, -Math.PI]}
        scale={[0.03, 1.85, 0.03]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={Materials.fenceMaterial}
        position={[-60.21, 16.58, -1.02]}
        rotation={[-Math.PI, 0.33, -Math.PI]}
        scale={2.6}
      />
      <group position={[-51.85, 12.91, -10.33]} rotation={[-Math.PI, 0.35, -Math.PI]} scale={0.47}>
        <mesh geometry={nodes.Plane007.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Plane007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.barHolder_2001.geometry}
        material={Materials.fenceMaterial}
        position={[-62.68, 12.41, -6.55]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={0.47}
      />
      <mesh
        geometry={nodes.barHolder_2.geometry}
        material={Materials.fenceMaterial}
        position={[-69.86, 12.41, -4.31]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={0.47}
      />
      <mesh
        geometry={nodes.barHolder_1001.geometry}
        material={Materials.fenceMaterial}
        position={[-64.92, 12.41, -13.73]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={0.47}
      />
      <mesh
        geometry={nodes.barHolder_1.geometry}
        material={Materials.fenceMaterial}
        position={[-72.1, 12.41, -11.49]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={0.47}
      />
      <group
        position={[-49.61, 16.84, -5.5]}
        rotation={[-Math.PI, 0.35, -Math.PI]}
        scale={[0.47, 0.55, 0.47]}
      >
        <mesh geometry={nodes.Cylinder011_1.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={Materials.fenceMaterial}
        position={[-42.69, 18.44, 6.82]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={[0.03, 0.36, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={Materials.fenceMaterial}
        position={[-46.75, 18.47, 4.63]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={[0.03, 0.24, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={Materials.fenceMaterial}
        position={[-33.74, 18.54, 11.58]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={[0.03, 0.47, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={Materials.fenceMaterial}
        position={[-37.89, 18.46, 9.35]}
        rotation={[-Math.PI, 1.27, -Math.PI]}
        scale={[0.03, 0.46, 0.03]}
      />
      <group
        position={[-36.24, 11.44, 1.68]}
        rotation={[-Math.PI, 0.52, -Math.PI]}
        scale={[0.29, 0.72, 0.29]}
      >
        <mesh geometry={nodes.Plane015.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Plane015_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Bar_3002.geometry}
        material={Materials.fenceMaterial}
        position={[-37.1, 17.5, -1.43]}
        rotation={[-Math.PI, 0.52, -Math.PI]}
        scale={[0.29, 0.85, 0.29]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={Materials.fenceMaterial}
        position={[-43.62, 14.85, 25.04]}
        rotation={[-0.02, 0.1, -0.63]}
        scale={[1.13, 0.13, 1.61]}
      />
      <group
        position={[-37.38, 15.14, 1.02]}
        rotation={[-0.02, -0.43, -0.64]}
        scale={[1.13, 0.13, 1.61]}
      >
        <mesh geometry={nodes.Cube028.geometry} material={Materials.metalMaterials.rusty} />
        <mesh geometry={nodes.Cube028_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-62.03, 14.53, -1.57]}
        rotation={[0, -0.43, -0.6]}
        scale={[1.13, 0.13, 1.61]}
      >
        <mesh geometry={nodes.Cube028.geometry} material={Materials.metalMaterials.rusty} />
        <mesh geometry={nodes.Cube028_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-37.25, 13.78, -0.11]} scale={[0.09, 1.37, 0.09]}>
        <mesh geometry={nodes.Cylinder028.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cylinder028_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.34, 13.51, -11.67]} rotation={[Math.PI / 2, 0, 0.32]} scale={0.49}>
        <mesh
          geometry={nodes.box3_v108_f74_Sphere004_1.geometry}
          material={Materials.treeMaterial}
        />
        <mesh
          geometry={nodes.box3_v108_f74_Sphere004_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-37.41, 15.65, -0.2]} rotation={[1.75, -0.44, 2.01]} scale={0.34}>
        <mesh
          geometry={nodes.box4_v95_f58_Sphere009_1.geometry}
          material={Materials.treeMaterial}
        />
        <mesh
          geometry={nodes.box4_v95_f58_Sphere009_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-36.97, 15.3, 0.02]} rotation={[1.73, -0.39, 2.01]} scale={0.34}>
        <mesh
          geometry={nodes.box4_v95_f58_Sphere009_1.geometry}
          material={Materials.treeMaterial}
        />
        <mesh
          geometry={nodes.box4_v95_f58_Sphere009_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-32.97, 13.64, -8.57]} rotation={[Math.PI / 2, 0, 2.17]} scale={0.34}>
        <mesh
          geometry={nodes.box5_540_f570_Sphere010_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.box5_540_f570_Sphere010_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-48.3, 13.7, -8.82]} rotation={[Math.PI / 2, 0, 1.87]} scale={0.44}>
        <mesh
          geometry={nodes.box6_v34_f19_Sphere015_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.box6_v34_f19_Sphere015_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-31.79, 13.3, 17.92]} rotation={[Math.PI / 2, 0, 1.54]} scale={0.44}>
        <mesh
          geometry={nodes.box6_v34_f19_Sphere015_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.box6_v34_f19_Sphere015_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-48.43, 13.6, -7.65]} rotation={[Math.PI / 2, 0, 1.87]} scale={0.44}>
        <mesh
          geometry={nodes.box7_v140_f78_Sphere017_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.box7_v140_f78_Sphere017_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-31.53, 13.2, 19.07]} rotation={[Math.PI / 2, 0, 1.54]} scale={0.44}>
        <mesh
          geometry={nodes.box7_v140_f78_Sphere017_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.box7_v140_f78_Sphere017_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-34.02, 13.63, -5.61]} rotation={[Math.PI / 2, 0, 1.03]} scale={0.34}>
        <mesh
          geometry={nodes.box_with_mesh_v602_f324_Sphere012_1.geometry}
          material={Materials.treeMaterial}
        />
        <mesh
          geometry={nodes.box_with_mesh_v602_f324_Sphere012_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-32.73, 13.79, -4.55]} rotation={[Math.PI / 2, 0, 2.02]} scale={0.37}>
        <mesh
          geometry={nodes.box_with_one_handle_v44_f30_Sphere016_1.geometry}
          material={Materials.treeMaterial}
        />
        <mesh
          geometry={nodes.box_with_one_handle_v44_f30_Sphere016_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-35.2, 13.48, 1.67]} rotation={[Math.PI / 2, 0, 2.06]} scale={0.34}>
        <mesh
          geometry={nodes.long_box_v124_f96__Sphere001_1.geometry}
          material={Materials.treeMaterial}
        />
        <mesh
          geometry={nodes.long_box_v124_f96__Sphere001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-34.38, 13.23, 3.03]} rotation={[Math.PI / 2, 0, 2.06]} scale={0.34}>
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere008_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere008_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-43.25, 13.27, 9.28]} rotation={[Math.PI / 2, 0, 0.51]} scale={0.34}>
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere008_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere008_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group
        position={[-48.96, 14.92, -6.11]}
        rotation={[Math.PI / 2, 0, -1.25]}
        scale={[0.34, 0.34, 0.4]}
      >
        <mesh
          geometry={nodes.shelving1_v359_f350_Sphere013_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.shelving1_v359_f350_Sphere013_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group
        position={[-31.65, 14.6, 20.94]}
        rotation={[Math.PI / 2, 0, -1.94]}
        scale={[0.34, 0.34, 0.4]}
      >
        <mesh
          geometry={nodes.shelving1_v359_f350_Sphere013_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.shelving1_v359_f350_Sphere013_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.shelving2_v562_f346_Sphere004.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-34.15, 19.18, 42.1]}
        rotation={[Math.PI / 2, 0, 3.11]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.shelving2_v562_f346_Sphere005.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-35.97, 19.22, 42.18]}
        rotation={[Math.PI / 2, 0, 3.11]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.shelving2_v562_f346_Sphere003.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-37.83, 19.22, 42.26]}
        rotation={[Math.PI / 2, 0, 3.11]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.shelving2_v562_f346_Sphere006.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-39.63, 19.22, 42.35]}
        rotation={[Math.PI / 2, 0, 3.11]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.shelving2_v562_f346_Sphere007.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-40.79, 14, 27.11]}
        rotation={[Math.PI / 2, 0, 3.09]}
        scale={0.34}
      />
      <group position={[-35.98, 14.19, 4.23]} rotation={[Math.PI / 2, 0, -2.66]} scale={0.34}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere014_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere014_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-58.79, 13.85, 0.82]} rotation={[Math.PI / 2, 0, -1.28]} scale={0.34}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere014_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere014_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-46.89, 14, 7.76]} rotation={[Math.PI / 2, 0, -1.04]} scale={0.34}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere014_1.geometry}
          material={Materials.metalMaterials.rusty}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere014_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-62.88, 13.21, -0.9]} scale={[0.09, 1.45, 0.09]}>
        <mesh geometry={nodes.Cylinder031.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cylinder031_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.fiberCover003.geometry}
        material={Materials.fenceMaterial}
        position={[-42.3, 11.15, 25.04]}
        rotation={[-Math.PI, -0.01, -Math.PI]}
        scale={[0.29, 0.72, 0.29]}
      />
      <mesh
        geometry={nodes.Bar_3003.geometry}
        material={Materials.fenceMaterial}
        position={[-44.62, 17.2, 22.79]}
        rotation={[-Math.PI, -0.01, -Math.PI]}
        scale={[0.29, 0.85, 0.29]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={Materials.fenceMaterial}
        position={[-44.08, 13.49, 24.01]}
        rotation={[0, 0.53, 0]}
        scale={[0.09, 1.37, 0.09]}
      />
      <mesh
        geometry={nodes.box4_v95_f58_Sphere004.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-44.27, 15.36, 24.01]}
        rotation={[1.48, -0.47, 1.42]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.box4_v95_f58_Sphere005.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-43.77, 15.01, 23.98]}
        rotation={[1.5, -0.41, 1.43]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.long_box_v124_f96__Sphere002.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-40.08, 13.33, 23.72]}
        rotation={[Math.PI / 2, 0, 1.53]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.long_wide_drawer_v156_f118_Sphere002.geometry}
        material={Materials.metalMaterials.rusty}
        position={[-40.02, 13.4, 25.26]}
        rotation={[Math.PI / 2, 0, 1.53]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={Materials.gasPumpMaterials.green}
        position={[48.91, 17.55, 4.11]}
        rotation={[Math.PI / 2, 0, -1.66]}
        scale={[0.58, 2.06, 0.6]}
      />
      <group position={[39.25, 13.06, -11.81]} rotation={[Math.PI, -1.56, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[39.13, 13.07, -12.57]} rotation={[Math.PI, -0.37, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[38.13, 13.12, -11.38]} rotation={[Math.PI, -0.14, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[38.42, 13.12, -12.33]} rotation={[0, 0.51, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[39.44, 13, -13.84]} rotation={[0, 1.19, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[39.7, 12.96, -13.06]} rotation={[0, -0.39, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[38.89, 13.04, -13.31]} rotation={[-Math.PI, -1.56, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[33.6, 13.01, -3.13]} rotation={[0, -0.06, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[32.94, 13.07, -3.6]} rotation={[Math.PI, -0.31, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[32.76, 13.12, -2.64]} rotation={[0, 0.45, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[33.48, 13, -4.93]} rotation={[0, 1.12, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[33.64, 12.96, -4.14]} rotation={[0, -0.45, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[32.77, 13.04, -4.42]} rotation={[-Math.PI, -1.5, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-8.88, 12.94, -12.89]} rotation={[Math.PI, -1.48, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-10.03, 13, -12.55]} rotation={[Math.PI, -0.05, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle038.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Circle038_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[48.67, 20.24, 4.13]} rotation={[0, 0.02, 0]} scale={[0.42, 3.82, 1.25]}>
        <mesh geometry={nodes.Cube033.geometry} material={Materials.gasPumpMaterials.white} />
        <mesh geometry={nodes.Cube033_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[48.99, 23.05, 4.15]}
        rotation={[Math.PI / 2, 0, 1.55]}
        scale={[-0.67, -0.34, 0.72]}
      >
        <mesh geometry={nodes.Curve003_1.geometry} material={Materials.gasPumpMaterials.green} />
        <mesh geometry={nodes.Curve003_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.petronas001_Cube_3_Instance_0006.geometry}
        material={Materials.fenceMaterial}
        position={[48.66, 13.21, 4.96]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={1.18}
      />
      <group position={[48.69, 15.86, 5.47]} rotation={[Math.PI / 2, 0, 3.12]} scale={1.18}>
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0007_1.geometry}
          material={Materials.fenceMaterial}
        />
        <mesh
          geometry={nodes.petronas001_Cube_3_Instance_0007_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.Curve003.geometry}
        material={Materials.outlineMaterial}
        position={[51, 16.3, 43.4]}
        rotation={[0, Math.PI / 4, -Math.PI / 4]}
        scale={1.7}
      />
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={Materials.roadMaterials.line}
        position={[77.52, 9.17, -6.23]}
        scale={[19.49, 200.26, 19.49]}
      />
      <group
        position={[-33.05, 19.72, 19.81]}
        rotation={[-3.14, 0.49, 1.59]}
        scale={[0.02, 0.2, 0.02]}
      >
        <mesh geometry={nodes.Cube194.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube194_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-31.62, 19.72, 16.94]}
        rotation={[-3.14, 0.49, 1.59]}
        scale={[0.02, 0.2, 0.02]}
      >
        <mesh geometry={nodes.Cube194.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube194_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-32.84, 17.31, 18.2]}
        rotation={[0, -0.49, -0.01]}
        scale={[0.12, 2.55, -3.62]}
      >
        <mesh geometry={nodes.Cube196.geometry} material={Materials.outlineMaterial} />
        <mesh
          geometry={nodes.Cube196_1.geometry}
          material={new MeshBasicMaterial({ map: pubTexture })}
        />
      </group>
      <group
        position={[-32.84, 17.31, 18.2]}
        rotation={[0, -0.49, -0.01]}
        scale={[0.12, 2.55, -3.62]}
      >
        <mesh geometry={nodes.Cube197.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Cube197_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-32.86, 15.43, 17.79]}
        rotation={[0, -0.49, -0.01]}
        scale={[-0.01, 0.01, 0.02]}
      >
        <mesh geometry={nodes.Mesh234.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh234_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-32.81, 18.89, 17.83]}
        rotation={[0, -0.49, -0.01]}
        scale={[-0.01, 0.01, 0.02]}
      >
        <mesh geometry={nodes.Mesh234.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh234_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Wheel_A001004.geometry}
        material={Materials.floorMaterial}
        position={[22.01, 13.9, 15.05]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A003.geometry}
        material={Materials.floorMaterial}
        position={[23.68, 13.9, 8.99]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A002.geometry}
        material={Materials.floorMaterial}
        position={[23.68, 13.9, 8.99]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A004.geometry}
        material={Materials.floorMaterial}
        position={[23.68, 13.9, 8.99]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body036.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body034.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body031.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body029.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body027.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body026.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body017.geometry}
        material={materials.Vitre}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body014.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body005.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body001.geometry}
        material={Materials.floorMaterial}
        position={[24.6, 15.01, 12.17]}
        rotation={[-Math.PI, 0.27, -Math.PI]}
        scale={0}
      />
      <group position={[24.6, 15.01, 12.17]} rotation={[-Math.PI, 0.27, -Math.PI]} scale={0}>
        <mesh geometry={nodes.Mesh239.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh239_1.geometry} material={Materials.outlineMaterial} />
      </group>
    </group>
  )
}
