/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.10 baobab_1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/scenes/baobab_1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-14.04, 12.17, 195.81]} rotation={[Math.PI, -0.2, Math.PI]} scale={[-3.59, 2.88, 3.29]}>
        <mesh geometry={nodes.Cube048.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube048_1.geometry} material={materials.Border} />
      </group>
      <group position={[-24.69, 10.67, 20.01]} rotation={[-Math.PI, 1.46, -Math.PI]} scale={[0.41, 0.41, 0.76]}>
        <mesh geometry={nodes.Cube057.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube057_1.geometry} material={materials.Border} />
      </group>
      <group position={[-27.27, 10.89, 12.73]} rotation={[-Math.PI, 0.78, -Math.PI]} scale={[1.23, 0.4, 1.19]}>
        <mesh geometry={nodes.Cube235.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube235_1.geometry} material={materials.Border} />
      </group>
      <group position={[-3.81, 11.81, 213.01]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={0.26}>
        <mesh geometry={nodes.Cube186.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube186_1.geometry} material={materials.Border} />
      </group>
      <group position={[-14.88, 11.91, 198.49]} rotation={[-Math.PI, -0.85, -Math.PI]} scale={[0.36, 0.26, 0.38]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Border} />
      </group>
      <group position={[-7.42, 12.81, 195.76]} rotation={[2.73, 1.47, -2.74]} scale={[0.16, 0.04, 0.07]}>
        <mesh geometry={nodes.Sphere008_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere008_2.geometry} material={materials.Border} />
      </group>
      <group position={[-7.66, 12.79, 196.18]} rotation={[2.42, 1.45, -2.44]} scale={[0.27, 0.07, 0.17]}>
        <mesh geometry={nodes.Sphere008_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere008_2.geometry} material={materials.Border} />
      </group>
      <group position={[-7.67, 11.98, 209.59]} rotation={[-0.18, -0.15, 1.78]} scale={[0.09, 0.09, 0.15]}>
        <mesh geometry={nodes.Sphere008_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere008_2.geometry} material={materials.Border} />
      </group>
      <group position={[-12.69, 12.56, 168.94]} rotation={[-2.81, 1.46, 2.81]} scale={[0.21, 0.05, 0.13]}>
        <mesh geometry={nodes.Sphere008_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere008_2.geometry} material={materials.Border} />
      </group>
      <group position={[-12.58, 12.53, 196.6]} rotation={[3.06, -0.67, 2.97]} scale={[0.13, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere014_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere014_2.geometry} material={materials.Border} />
      </group>
      <group position={[-4.65, 12.51, 207.44]} rotation={[-2.88, 1.15, 3.06]} scale={[0.13, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere014_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere014_2.geometry} material={materials.Border} />
      </group>
      <group position={[-8.06, 11.97, 209.56]} rotation={[0.14, -0.98, 0.18]} scale={[0.15, 0.15, 0.26]}>
        <mesh geometry={nodes.Sphere010_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere010_2.geometry} material={materials.Border} />
      </group>
      <group position={[-4.28, 12.18, 202.61]} rotation={[0.01, 0.02, 0.08]} scale={[0.25, 0.13, 0.22]}>
        <mesh geometry={nodes.Sphere009_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere009_2.geometry} material={materials.Border} />
      </group>
      <group position={[-32.63, 12.2, 193.79]} rotation={[0.01, 0.02, 0.08]} scale={[0.34, 0.17, 0.31]}>
        <mesh geometry={nodes.Sphere009_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere009_2.geometry} material={materials.Border} />
      </group>
      <group position={[-12.93, 12.49, 197.81]} rotation={[3.12, -0.74, 3.05]} scale={[0.32, 0.17, 0.29]}>
        <mesh geometry={nodes.Sphere013_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere013_2.geometry} material={materials.Border} />
      </group>
      <group position={[-5.06, 12.55, 206.6]} rotation={[-2.97, 1.12, 3.05]} scale={[0.43, 0.22, 0.39]}>
        <mesh geometry={nodes.Sphere013_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere013_2.geometry} material={materials.Border} />
      </group>
      <group position={[-11.97, 12.57, 168.22]} rotation={[-0.11, 0.94, 2.53]} scale={[0.06, 0.06, 0.11]}>
        <mesh geometry={nodes.Sphere007_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere007_2.geometry} material={materials.Border} />
      </group>
      <group position={[-12.41, 12.55, 168.13]} rotation={[-2.81, 1.46, 2.81]} scale={[0.43, 0.1, 0.19]}>
        <mesh geometry={nodes.Sphere005_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere005_2.geometry} material={materials.Border} />
      </group>
      <group position={[-19.84, 12.41, 189.33]} rotation={[-0.14, 0.71, 1.95]} scale={[0.06, 0.06, 0.11]}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials.Border} />
      </group>
      <group position={[-20.01, 12.36, 189.53]} rotation={[0.43, 0, 0]} scale={[0.1, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials.Border} />
      </group>
      <group position={[-10.25, 10.44, 81.77]} scale={[174.33, 78.88, 73.17]}>
        <mesh geometry={nodes.Plane006.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.Border} />
      </group>
      <group position={[-148.48, 8.94, -634.25]} rotation={[0.33, 0.15, -0.04]} scale={[552.83, 96.68, 78.63]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials.Border} />
      </group>
      <group position={[-112.45, 7.52, -264.98]} rotation={[0.17, 0, 0]} scale={[506.75, 81.86, 137.18]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.Border} />
      </group>
      <group position={[-1.64, 11.02, 81.77]} scale={[174.33, 43.66, 73.17]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.Border} />
      </group>
      <group position={[-19.28, 12.07, 149.35]} scale={[174.33, 26.31, -79.77]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.Border} />
      </group>
      <group position={[242.39, 14.49, -379.14]} rotation={[Math.PI / 2, 0, 2.59]} scale={[-0.02, 0.03, 0.01]}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.Border} />
      </group>
      <group position={[247.67, 14.2, -570.91]} rotation={[Math.PI / 2, 0, -0.03]} scale={[0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh027.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={materials.Border} />
      </group>
      <group position={[-221.23, 18.22, -570.91]} rotation={[Math.PI / 2, 0, 1.96]} scale={[0.04, 0.03, 0.01]}>
        <mesh geometry={nodes.Mesh024.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh024_1.geometry} material={materials.Border} />
      </group>
      <group position={[120.23, 16.25, -576.83]} rotation={[Math.PI / 2, 0, -3.13]} scale={[-0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh014.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={materials.Border} />
      </group>
      <group position={[-571.23, 16.25, -568.84]} rotation={[Math.PI / 2, 0, 3.13]} scale={[0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh006.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials.Border} />
      </group>
      <group position={[-345.6, 5.5, -442.05]} rotation={[Math.PI / 2, 0, 2.98]} scale={[0.03, 0.04, 0.02]}>
        <mesh geometry={nodes.Mesh061.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh061_1.geometry} material={materials.Border} />
      </group>
      <group position={[-105.89, 16.25, -576.83]} rotation={[Math.PI / 2, 0, 3.13]} scale={[0.04, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Border} />
      </group>
      <group position={[-368.37, 2.9, -265.17]} rotation={[Math.PI / 2, 0, 1.38]} scale={0.01}>
        <mesh geometry={nodes.Mesh012.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={materials.Border} />
      </group>
      <group position={[-117.72, 3.23, -300.92]} rotation={[Math.PI / 2, 0, 1.76]} scale={[0.01, 0.04, 0.01]}>
        <mesh geometry={nodes.Mesh054.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh054_1.geometry} material={materials.Border} />
      </group>
      <group position={[63.04, 5.42, -265.17]} rotation={[Math.PI / 2, 0, 2.48]} scale={0.01}>
        <mesh geometry={nodes.Mesh053.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh053_1.geometry} material={materials.Border} />
      </group>
      <group position={[-19.46, 23.62, 196.67]} rotation={[-0.31, -1.06, -0.35]} scale={[-1.26, 0.65, 1.78]}>
        <mesh geometry={nodes.Icosphere007.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Icosphere007_1.geometry} material={materials.Border} />
      </group>
      <group position={[-16.13, 23.34, 197.62]} rotation={[2.7, 1.37, -2.71]} scale={[-1.26, 0.47, 1.3]}>
        <mesh geometry={nodes.Icosphere007.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Icosphere007_1.geometry} material={materials.Border} />
      </group>
      <group position={[-9.73, 22.78, 194.88]} rotation={[-2.36, -1.36, -2.46]} scale={[-1.73, 0.65, 1.79]}>
        <mesh geometry={nodes.Icosphere007.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Icosphere007_1.geometry} material={materials.Border} />
      </group>
      <group position={[-14.89, 23.74, 191.68]} rotation={[0.02, 0.65, -0.01]} scale={[-1.44, 0.64, 2.43]}>
        <mesh geometry={nodes.Icosphere006.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Icosphere006_1.geometry} material={materials.Border} />
      </group>
      <group position={[-12.73, 22.38, 200.73]} rotation={[3.12, -0.34, 3.14]} scale={[-1.2, 0.64, 2.17]}>
        <mesh geometry={nodes.Icosphere006.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Icosphere006_1.geometry} material={materials.Border} />
      </group>
      <group position={[-19.91, 11.71, 215.19]} rotation={[-3.03, -0.21, 3.13]} scale={[-0.86, 0.86, 0.86]}>
        <mesh geometry={nodes.Circle192.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle192_1.geometry} material={materials.Border} />
      </group>
      <group position={[-30.17, 12.34, 15.17]} rotation={[-0.51, -0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle127_1.geometry} material={materials.Border} />
      </group>
      <group position={[-6.69, 12.48, 202.9]} rotation={[0, -0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle127_1.geometry} material={materials.Border} />
      </group>
      <group position={[-37.12, 12.41, 188.46]} rotation={[3.12, 0.06, -3.14]} scale={0.95}>
        <mesh geometry={nodes.Circle110.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle110_1.geometry} material={materials.Border} />
      </group>
      <group position={[-36.79, 12.27, 205.18]} rotation={[3.11, -0.36, 3.13]} scale={0.95}>
        <mesh geometry={nodes.Circle109.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle109_1.geometry} material={materials.Border} />
      </group>
      <group position={[-56.18, 12.18, 134.19]} rotation={[0.23, 0.62, -0.04]} scale={0.95}>
        <mesh geometry={nodes.Circle107.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle107_1.geometry} material={materials.Border} />
      </group>
      <group position={[-45.76, 11.86, 132.87]} rotation={[0.38, 0, -0.02]} scale={0.95}>
        <mesh geometry={nodes.Circle104.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle104_1.geometry} material={materials.Border} />
      </group>
      <group position={[-32.37, 12.27, 182.25]} rotation={[0.04, 0.23, -0.05]} scale={[-0.95, 0.95, 0.95]}>
        <mesh geometry={nodes.Circle771.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle771_1.geometry} material={materials.Border} />
      </group>
      <group position={[-20.74, 12.31, 169.44]} rotation={[0.03, 0, 0]} scale={0.95}>
        <mesh geometry={nodes.Circle543.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle543_1.geometry} material={materials.Border} />
      </group>
      <group position={[-6.36, 12.29, 201.02]} rotation={[3.13, -0.2, 3.14]} scale={[-0.86, 0.86, 0.86]}>
        <mesh geometry={nodes.Circle006.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle006_1.geometry} material={materials.Border} />
      </group>
      <group position={[-4.8, 12.16, 215.48]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.28}>
        <mesh geometry={nodes.Circle218.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle218_1.geometry} material={materials.Border} />
      </group>
      <group position={[-14.59, 12.42, 140.9]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.99}>
        <mesh geometry={nodes.Circle218.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle218_1.geometry} material={materials.Border} />
      </group>
      <group position={[8.39, 12.31, 202.15]} rotation={[-Math.PI, 0.21, -Math.PI]} scale={1.12}>
        <mesh geometry={nodes.Circle773.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Circle773_1.geometry} material={materials.Border} />
      </group>
      <group position={[-124.37, 18.33, 59.44]} rotation={[-0.11, -0.98, -0.06]} scale={0.01}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.Border} />
      </group>
      <group position={[-84.71, 18.33, 95.46]} rotation={[-0.08, 0.63, 0.07]} scale={0.02}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.Border} />
      </group>
      <group position={[-124.8, 18.33, 97.91]} rotation={[-0.11, -0.98, -0.06]} scale={0.01}>
        <mesh geometry={nodes.Mesh009.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.Border} />
      </group>
      <mesh geometry={nodes.Plane001001.geometry} material={materials['Wood cercles']} position={[-106.06, 23.28, 95.31]} rotation={[Math.PI, -0.89, Math.PI]} scale={[-0.04, 0.04, -0.04]} />
      <mesh geometry={nodes.Plane001003.geometry} material={materials['Wood cercles']} position={[-110.41, 17.59, 100.57]} rotation={[0, -0.68, 0]} scale={[0.07, 0.06, 0.06]} />
      <mesh geometry={nodes.group_0_ID4002.geometry} material={materials['Wood cercles']} position={[-122.3, 14.6, 12.33]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.group_0_ID4003.geometry} material={materials['Wood cercles']} position={[-122.3, 10.35, 12.33]} rotation={[Math.PI / 2, 0, 1.57]} scale={1.34} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Wood cercles']} position={[-104.44, 19.68, 93.12]} rotation={[Math.PI, -0.89, Math.PI]} scale={[7.65, 3.05, 10.1]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Wood cercles']} position={[-104.4, 14.09, 93.47]} rotation={[Math.PI, -0.89, Math.PI]} scale={[7.5, 2.54, 10.01]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Wood cercles']} position={[-107.42, 14.34, 43.43]} rotation={[Math.PI, -1.57, Math.PI]} scale={[7.87, 2.66, 12.52]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Wood cercles']} position={[-107.42, 23.81, 43.43]} rotation={[Math.PI, -1.57, Math.PI]} scale={[8.02, 1.32, 13.82]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Wood cercles']} position={[-107.86, 19.76, 43.43]} rotation={[Math.PI, -1.57, Math.PI]} scale={[7.87, 2.76, 13.82]} />
      <mesh geometry={nodes.Box001001.geometry} material={materials['Wood cercles']} position={[-107.39, 25.07, 36.21]} rotation={[1.57, 0, 1.57]} scale={[0.29, -0.3, -0.3]} />
      <mesh geometry={nodes.Box001002.geometry} material={materials['Wood cercles']} position={[-107.43, 18.31, 52.42]} rotation={[-1.58, 0, 0]} scale={[0.28, 0.3, -0.3]} />
      <group position={[-87.54, 18.21, 76.21]} rotation={[3.14, -0.29, 3.14]} scale={0.01}>
        <mesh geometry={nodes.Mesh041.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh041_1.geometry} material={materials.Border} />
      </group>
      <group position={[24.96, 13.42, 103.93]} rotation={[0, -0.44, 0]} scale={1.42}>
        <mesh geometry={nodes.Cube058.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube058_1.geometry} material={materials.Border} />
      </group>
      <group position={[28.56, 11.5, 68.48]} rotation={[0, 0.69, -0.01]} scale={[-0.74, 0.74, 0.74]}>
        <mesh geometry={nodes.Cube179.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube179_1.geometry} material={materials.Border} />
      </group>
      <group position={[31.21, 20.01, 68.42]} rotation={[0, 0.69, -0.12]} scale={[-0.74, 0.74, 0.74]}>
        <mesh geometry={nodes.Cube177.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube177_1.geometry} material={materials.Border} />
      </group>
      <group position={[26.76, 18.41, 70.43]} rotation={[0, 0.24, -0.12]} scale={[-0.38, 0.38, 0.38]}>
        <mesh geometry={nodes.Cube176.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube176_1.geometry} material={materials.Border} />
      </group>
      <group position={[31.57, 23.22, 112.13]} rotation={[2.96, -1.16, 2.78]} scale={[-0.74, 0.74, 0.74]}>
        <mesh geometry={nodes.Cube168.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube168_1.geometry} material={materials.Border} />
      </group>
      <group position={[35.65, 18.69, 100.37]} rotation={[Math.PI, -1.18, -3.01]} scale={[-0.68, 0.56, 0.72]}>
        <mesh geometry={nodes.Cube167.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube167_1.geometry} material={materials.Border} />
      </group>
      <group position={[32.93, 22.73, 101.54]} rotation={[-Math.PI, -1.18, -Math.PI]} scale={[-0.96, 0.8, 1.02]}>
        <mesh geometry={nodes.Cube166.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube166_1.geometry} material={materials.Border} />
      </group>
      <group position={[34.37, 11.56, 106.92]} rotation={[-Math.PI, -1.18, -Math.PI]} scale={[-0.74, 0.74, 0.74]}>
        <mesh geometry={nodes.Cube158_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube158_2.geometry} material={materials.Border} />
      </group>
      <group position={[18.95, 24.67, 102.23]} rotation={[-0.09, 0.03, 0.07]} scale={[-0.96, 0.8, 1.02]}>
        <mesh geometry={nodes.Cube142.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube142_1.geometry} material={materials.Border} />
      </group>
      <group position={[19.28, 26.55, 107.14]} rotation={[0, 1.04, 0]} scale={[-0.96, 0.8, 1.02]}>
        <mesh geometry={nodes.Cube141.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube141_1.geometry} material={materials.Border} />
      </group>
      <group position={[17.89, 17.28, 107.88]} rotation={[0, 1.04, 0]} scale={[-0.82, 0.74, 0.54]}>
        <mesh geometry={nodes.Cube139.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube139_1.geometry} material={materials.Border} />
      </group>
      <group position={[19.37, 11.31, 104.35]} rotation={[0, 1.04, 0]} scale={[-0.74, 0.74, 0.74]}>
        <mesh geometry={nodes.Cube137_1.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Cube137_2.geometry} material={materials.Border} />
      </group>
      <mesh geometry={nodes.Plateau_winter_004001.geometry} material={materials['Wood cercles']} position={[42.75, 10.63, 40.01]} rotation={[Math.PI / 2, 0, -2.17]} scale={0.01} />
      <group position={[20.21, 10.16, 62.28]} rotation={[Math.PI / 2, 0, -0.56]} scale={[0.02, 0.01, 0.01]}>
        <mesh geometry={nodes.Mesh055.geometry} material={materials['Wood cercles']} />
        <mesh geometry={nodes.Mesh055_1.geometry} material={materials.Border} />
      </group>
      <mesh geometry={nodes.tronco005.geometry} material={materials['Material.010']} position={[-76.51, 10.87, 74]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={0.25} />
      <mesh geometry={nodes.tronco004.geometry} material={materials['Material.010']} position={[-74.28, 10.58, 80.31]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={0.25} />
      <mesh geometry={nodes.tronco003.geometry} material={materials['Material.010']} position={[-82.4, 10.7, 78.99]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={0.25} />
      <group position={[-76.51, 10.85, 74]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={0.25}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-73.14, 21.52, 81.69]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={0.25}>
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-83.27, 20.81, 78.5]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={0.25}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[29.99, 4.29, 110.82]} rotation={[Math.PI / 2, 0, -1.08]} scale={[0.01, 0.02, 0.01]}>
        <mesh geometry={nodes.Mesh057.geometry} material={materials.Border} />
        <mesh geometry={nodes.Mesh057_1.geometry} material={materials['Wood cercles']} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/scenes/baobab_1.glb')
