/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.10 BaobabTwo.glb --transform
*/

import React, { useState, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import { getMaterials } from "@/helpers/materials/Materials"
import { useControls } from "leva"

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/scenes/baobab_2.glb")

  const [Materials, setMaterials] = useState(null)

  useEffect(() => {
    getMaterials("default").then((result) => setMaterials(result))
  }, [])

  if (Materials === null) {
    return <group></group>
  }

  return (
    <group {...props} dispose={null}>
      <group
        position={[-24.69, 10.67, 20.01]}
        rotation={[-Math.PI, 1.46, -Math.PI]}
        scale={[0.41, 0.41, 0.76]}
      >
        <mesh geometry={nodes.Cube057.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube057_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-3.81, 11.63, 213.01]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={0.26}>
        <mesh geometry={nodes.Cube186.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube186_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-14.88, 11.91, 189.42]}
        rotation={[Math.PI, -0.85, Math.PI]}
        scale={[0.43, 0.31, 0.45]}
      >
        <mesh geometry={nodes.Cube005.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Cube005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-7.42, 12.81, 195.76]}
        rotation={[2.73, 1.47, -2.74]}
        scale={[0.16, 0.04, 0.07]}
      >
        <mesh geometry={nodes.Sphere008_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere008_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-10.88, 12.57, 197.59]}
        rotation={[3.06, -0.67, 2.97]}
        scale={[0.13, 0.1, 0.18]}
      >
        <mesh geometry={nodes.Sphere014_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere014_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-7.66, 12.79, 196.18]}
        rotation={[2.42, 1.45, -2.44]}
        scale={[0.27, 0.07, 0.17]}
      >
        <mesh geometry={nodes.Sphere012_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere012_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-7.67, 11.98, 209.59]}
        rotation={[-0.18, -0.15, 1.78]}
        scale={[0.09, 0.09, 0.15]}
      >
        <mesh geometry={nodes.Sphere012_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere012_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-13.61, 12.15, 155.32]}
        rotation={[-2.81, 1.46, 2.81]}
        scale={[0.21, 0.05, 0.13]}
      >
        <mesh geometry={nodes.Sphere012_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere012_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-8.06, 12.37, 209.56]}
        rotation={[0.14, -0.98, 0.18]}
        scale={[0.15, 0.15, 0.26]}
      >
        <mesh geometry={nodes.Sphere010_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere010_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-4.28, 12.5, 202.61]}
        rotation={[0.01, 0.02, 0.08]}
        scale={[0.25, 0.13, 0.22]}
      >
        <mesh geometry={nodes.Sphere009_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere009_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-11.35, 12.59, 198.8]}
        rotation={[3.12, -0.74, 3.05]}
        scale={[0.32, 0.17, 0.29]}
      >
        <mesh geometry={nodes.Sphere013_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere013_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-12.33, 12.2, 155.18]}
        rotation={[-0.03, 0.96, 2.4]}
        scale={[0.06, 0.06, 0.11]}
      >
        <mesh geometry={nodes.Sphere007_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere007_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-13.24, 12.15, 155.21]}
        rotation={[-2.81, 1.46, 2.81]}
        scale={[0.43, 0.1, 0.19]}
      >
        <mesh geometry={nodes.Sphere005_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere005_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-4.65, 12.51, 207.44]}
        rotation={[-2.88, 1.15, 3.06]}
        scale={[0.13, 0.1, 0.18]}
      >
        <mesh geometry={nodes.Sphere004_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-32.63, 12.4, 193.79]}
        rotation={[0.01, 0.02, 0.08]}
        scale={[0.34, 0.17, 0.31]}
      >
        <mesh geometry={nodes.Sphere003_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-19.84, 12.48, 189.33]}
        rotation={[-0.14, 0.71, 1.95]}
        scale={[0.06, 0.06, 0.11]}
      >
        <mesh geometry={nodes.Sphere002_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-5.06, 12.55, 206.6]}
        rotation={[-2.97, 1.12, 3.05]}
        scale={[0.43, 0.22, 0.39]}
      >
        <mesh geometry={nodes.Sphere001_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-20.01, 12.4, 189.53]} rotation={[0.43, 0, 0]} scale={[0.1, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere_1.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Sphere_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-10.25, 10.44, 81.77]} scale={[174.33, 57.7, 73.17]}>
        <mesh geometry={nodes.Plane006.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Plane006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-126.05, 4.24, -634.25]}
        rotation={[0.33, 0.15, -0.04]}
        scale={[1100.29, 180.92, 81.36]}
      >
        <mesh geometry={nodes.Plane005.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Plane005_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-100.08, 7.52, -264.98]}
        rotation={[0.17, 0, 0]}
        scale={[603.92, 81.86, 137.18]}
      >
        <mesh geometry={nodes.Plane003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-1.64, 11.02, 81.77]} scale={[442.54, 62.21, 73.17]}>
        <mesh geometry={nodes.Plane004.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-19.28, 12.07, 149.35]}
        rotation={[0, 0, -Math.PI]}
        scale={[-174.33, -26.31, -79.77]}
      >
        <mesh geometry={nodes.Plane002.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane002_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[242.39, 14.49, -379.14]}
        rotation={[-Math.PI / 2, 0, -2.59]}
        scale={[-0.02, -0.03, -0.01]}
      >
        <mesh geometry={nodes.Mesh001.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-442.19, 17.57, -362.53]}
        rotation={[Math.PI / 2, 0, -2.59]}
        scale={[0.02, 0.03, 0.01]}
      >
        <mesh geometry={nodes.Mesh001.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[247.67, 14.2, -570.91]}
        rotation={[Math.PI / 2, 0, -0.03]}
        scale={[0.04, 0.02, 0.01]}
      >
        <mesh geometry={nodes.Mesh027.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh027_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-221.23, 18.22, -570.91]}
        rotation={[Math.PI / 2, 0, 1.96]}
        scale={[0.04, 0.03, 0.01]}
      >
        <mesh geometry={nodes.Mesh024.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh024_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[120.23, 16.25, -576.83]}
        rotation={[-Math.PI / 2, 0, 3.13]}
        scale={[-0.04, -0.02, -0.01]}
      >
        <mesh geometry={nodes.Mesh014.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-571.23, 16.25, -568.84]}
        rotation={[Math.PI / 2, 0, 3.13]}
        scale={[0.04, 0.02, 0.01]}
      >
        <mesh geometry={nodes.Mesh006.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-333.4, 5.5, -442.05]}
        rotation={[Math.PI / 2, 0, 2.98]}
        scale={[0.03, 0.04, 0.02]}
      >
        <mesh geometry={nodes.Mesh061.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh061_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-105.89, 16.25, -576.83]}
        rotation={[Math.PI / 2, 0, 3.13]}
        scale={[0.04, 0.02, 0.01]}
      >
        <mesh geometry={nodes.Mesh003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-368.37, 2.9, -265.17]} rotation={[Math.PI / 2, 0, 1.38]} scale={0.01}>
        <mesh geometry={nodes.Mesh003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[63.04, 5.42, -265.17]} rotation={[Math.PI / 2, 0, 2.48]} scale={0.01}>
        <mesh geometry={nodes.Mesh003.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-117.72, 3.23, -300.92]}
        rotation={[Math.PI / 2, 0, 1.76]}
        scale={[0.01, 0.04, 0.01]}
      >
        <mesh geometry={nodes.Mesh054.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh054_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-30.17, 12.34, 15.17]} rotation={[-0.51, -0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-0.38, 11.87, 194.29]} rotation={[0, 0.96, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-0.53, 12.3, 196.14]} rotation={[0, 0.37, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-0.77, 12.06, 195.3]} rotation={[0, 1.56, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-1.34, 12.39, 195.83]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[0.44, 12.15, 196.22]} rotation={[-Math.PI, 0.68, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[1.44, 11.79, 196.14]} rotation={[0, -1.05, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[0.07, 12.27, 195.65]} rotation={[0, -0.82, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[1.01, 11.98, 195.26]} rotation={[0, 0.37, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.91, 12.14, 204.75]} rotation={[Math.PI, -1.36, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.17, 12.04, 205.15]} rotation={[0, -0.59, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-21.03, 12.03, 204.33]} rotation={[0, 0.99, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.56, 12.13, 205.61]} rotation={[0, 0.32, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.14, 12.2, 206.49]} rotation={[-Math.PI, 0.06, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.83, 12.15, 205.52]} rotation={[Math.PI, -0.18, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.85, 12.16, 206.28]} rotation={[Math.PI, -1.37, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-53.63, 12.71, 141.91]} rotation={[Math.PI, -0.62, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-53.35, 12.34, 142.7]} rotation={[0, -1.33, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-52.93, 12.42, 142.02]} rotation={[0, 0.25, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-54.69, 12.69, 142.11]} rotation={[0, -0.42, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-55.53, 12.35, 142.36]} rotation={[-Math.PI, 0.8, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-54.09, 12.63, 142.53]} rotation={[-Math.PI, 0.56, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-54.62, 12.61, 143.08]} rotation={[Math.PI, -0.63, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-47.66, 12.51, 171.4]} rotation={[Math.PI, -0.56, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-47.44, 12.43, 172.21]} rotation={[0, -1.4, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.92, 12.47, 171.58]} rotation={[0, 0.18, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-48.74, 12.59, 171.53]} rotation={[0, -0.49, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-49.7, 12.59, 171.79]} rotation={[-Math.PI, 0.86, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-48.16, 12.53, 171.99]} rotation={[-Math.PI, 0.63, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-48.73, 12.53, 172.5]} rotation={[Math.PI, -0.56, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.39, 12.51, 168.73]} rotation={[Math.PI, -0.27, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.4, 12.32, 169.57]} rotation={[Math.PI, -1.46, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-45.72, 12.47, 169.1]} rotation={[0, -0.11, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-47.45, 12.59, 168.54]} rotation={[0, -0.78, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-48.13, 12.59, 168.52]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-47.03, 12.53, 169.15]} rotation={[-Math.PI, 0.92, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-47.72, 12.53, 169.48]} rotation={[Math.PI, -0.27, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.2, 12.2, 205.58]} rotation={[0, -0.01, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-44.94, 12.04, 141.92]} rotation={[Math.PI, -1.36, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-44.2, 11.94, 142.32]} rotation={[0, -0.59, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-45.59, 12.03, 142.78]} rotation={[0, 0.32, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.17, 12.1, 143.66]} rotation={[-Math.PI, 0.06, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-44.86, 12.06, 142.69]} rotation={[Math.PI, -0.18, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-44.88, 12.06, 143.45]} rotation={[Math.PI, -1.37, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-46.23, 12.1, 142.75]} rotation={[0, -0.01, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22.74, 12.3, 170.21]} rotation={[Math.PI, -1.36, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-22, 12.48, 170.61]} rotation={[0, -0.59, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.74, 12.46, 171.08]} rotation={[0, 0.32, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.32, 12.43, 171.96]} rotation={[-Math.PI, 0.06, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.01, 12.51, 170.99]} rotation={[Math.PI, -0.18, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-23.03, 12.48, 171.75]} rotation={[Math.PI, -1.37, Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-24.38, 12.43, 171.05]} rotation={[0, -0.01, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle127.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle127_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Grass01.geometry}
        material={Materials.floorMaterial}
        position={[2.98, 14.53, 228.9]}
        scale={1.81}
      />
      <group position={[-5.76, 12.46, 207.38]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.28}>
        <mesh geometry={nodes.Circle218.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle218_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-14.59, 12.42, 140.9]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.99}>
        <mesh geometry={nodes.Circle218.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle218_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-25.26, 12.47, 170.45]} rotation={[-Math.PI, 1, -Math.PI]} scale={1.46}>
        <mesh geometry={nodes.Circle218.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Circle218_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Grass00.geometry}
        material={Materials.floorMaterial}
        position={[4.12, 14.53, 228.9]}
        scale={1.81}
      />
      <mesh
        geometry={nodes.Bush00.geometry}
        material={Materials.floorMaterial}
        position={[0.7, 14.53, 228.9]}
        scale={0.97}
      />
      <group
        position={[-89.9, 9.05, 67.33]}
        rotation={[0, 0, -Math.PI]}
        scale={[-32.05, -2.81, -46.43]}
      >
        <mesh geometry={nodes.Cube012.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-94.93, 21.04, 97.41]} rotation={[-0.04, 0.64, 0.02]} scale={0.01}>
        <mesh geometry={nodes.Mesh051.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh051_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[32.89, 13.66, 103.86]} rotation={[0, -0.44, 0]} scale={1.62}>
        <mesh geometry={nodes.Cube058.geometry} material={Materials.megalithicMaterial} />
        <mesh geometry={nodes.Cube058_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[38.8, 23.22, 112.13]} rotation={[-0.18, 1.16, -2.78]} scale={-0.74}>
        <mesh geometry={nodes.Cube168.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube168_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[42.89, 18.69, 100.37]}
        rotation={[0, 1.18, 3.01]}
        scale={[-0.68, -0.56, -0.72]}
      >
        <mesh geometry={nodes.Cube167.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube167_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[40.17, 22.73, 101.54]}
        rotation={[0, 1.18, -Math.PI]}
        scale={[-0.96, -0.8, -1.02]}
      >
        <mesh geometry={nodes.Cube166.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube166_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[41.6, 11.56, 106.92]} rotation={[0, 1.18, -Math.PI]} scale={-0.74}>
        <mesh geometry={nodes.Cube158.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube158_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[26.19, 24.67, 99.75]}
        rotation={[3.05, -0.03, -0.07]}
        scale={[-0.96, -0.8, -1.02]}
      >
        <mesh geometry={nodes.Cube142.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube142_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[26.51, 26.55, 107.14]}
        rotation={[Math.PI, -1.04, 0]}
        scale={[-0.96, -0.8, -1.02]}
      >
        <mesh geometry={nodes.Cube141.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube141_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[29.03, 20.94, 101.68]}
        rotation={[-2.86, -1.04, 0.36]}
        scale={[0.69, 0.77, 0.45]}
      >
        <mesh geometry={nodes.Cube139.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube139_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[26.6, 11.31, 104.35]} rotation={[Math.PI, -1.04, 0]} scale={-0.74}>
        <mesh geometry={nodes.Cube137_1.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube137_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[3.53, 10.16, 62.28]}
        rotation={[Math.PI / 2, 0, -0.56]}
        scale={[0.02, 0.01, 0]}
      >
        <mesh geometry={nodes.Mesh055.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Mesh055_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[37.22, -0.1, 110.82]}
        rotation={[Math.PI / 2, 0, -1.08]}
        scale={[0.01, 0.02, 0.01]}
      >
        <mesh geometry={nodes.Mesh057.geometry} material={Materials.grassMaterial} />
        <mesh geometry={nodes.Mesh057_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-20.77, 20.15, 205.78]} rotation={[0, -0.22, 0]} scale={0.02}>
        <mesh geometry={nodes.Mesh002.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-88.17, 19.78, 44.09]} rotation={[0.03, -1.5, 0.03]} scale={0.02}>
        <mesh geometry={nodes.Mesh002.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[25.45, 16.72, 107.87]} rotation={[-2.95, -0.17, 0.02]} scale={-0.38}>
        <mesh geometry={nodes.Cube001_1.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube001_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[332.47, 29.37, -1071.2]}
        rotation={[-Math.PI / 2, 0, -2.48]}
        scale={[-0.11, -0.13, -0.11]}
      >
        <mesh geometry={nodes.Mesh064.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Mesh064_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-2.76, 31.67, -1095.04]}
        rotation={[Math.PI / 2, 0, 1.32]}
        scale={[0.11, 0.07, 0.05]}
      >
        <mesh geometry={nodes.Mesh004.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[83.44, 10.16, 62.28]}
        rotation={[-Math.PI / 2, 0, -0.56]}
        scale={[-0.02, -0.01, 0]}
      >
        <mesh geometry={nodes.Mesh040.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh040_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[9.76, 11.51, 175.89]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={0.26}>
        <mesh geometry={nodes.Cube008_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube008_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[26.13, 11.58, 154.46]} rotation={[0, 1.12, 0]} scale={0.33}>
        <mesh geometry={nodes.Cube008_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube008_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-27.59, 11.72, 194.61]} rotation={[-0.11, -0.94, -0.01]} scale={0}>
        <mesh geometry={nodes.Mesh296.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh296_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-13.69, 19.31, 184.49]}
        rotation={[-3.13, -1.41, -0.03]}
        scale={[-2.61, -2.79, -3.21]}
      >
        <mesh geometry={nodes.Cube051.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Cube051_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-12.21, 27.32, 181.95]}
        rotation={[0.01, 1.14, -3.07]}
        scale={[-6.19, -1.83, -5.93]}
      >
        <mesh geometry={nodes.Icosphere010.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Icosphere010_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-18.04, 25.35, 189.13]}
        rotation={[0.25, -0.93, -2.86]}
        scale={[-2.24, -0.84, -2.33]}
      >
        <mesh geometry={nodes.Icosphere012.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Icosphere012_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-22.65, 24.96, 182.41]}
        rotation={[-3.04, -1.41, 0.1]}
        scale={[-1.7, -0.9, -3.06]}
      >
        <mesh geometry={nodes.Icosphere009.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Icosphere009_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-9.38, 22.59, 186.37]} rotation={[0, 1.26, 0]} scale={[1.35, 0.88, 1.81]}>
        <mesh geometry={nodes.Icosphere011.geometry} material={Materials.leafMaterial} />
        <mesh geometry={nodes.Icosphere011_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-16.13, 23.07, 182.93]}
        rotation={[Math.PI, -1.26, 0]}
        scale={[-4.66, -3.74, -4.26]}
      >
        <mesh geometry={nodes.Cube050.geometry} material={Materials.treeMaterial} />
        <mesh geometry={nodes.Cube050_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[800.26, 9.48, -2332.17]}
        rotation={[1.57, 0, -5.7]}
        scale={[0.4, 0.9, 0.5]}
      >
        <mesh geometry={nodes.Mesh052.geometry} material={Materials.stoneMaterial} />
        <mesh geometry={nodes.Mesh052_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-21.6, 13.13, 208.32]} rotation={[Math.PI, 0.67, 0]} scale={-0.02}>
        <mesh geometry={nodes.Mesh056.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh056_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[3.43, 13.13, 190.74]} rotation={[0, -0.63, -Math.PI]} scale={-0.02}>
        <mesh geometry={nodes.Mesh056.geometry} material={Materials.fenceMaterial} />
        <mesh geometry={nodes.Mesh056_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={Materials.roadMaterials.line}
        position={[20.46, 12.31, 156.44]}
        rotation={[0, -0.32, 0]}
        scale={10.27}
      />
      <mesh
        geometry={nodes.Route001.geometry}
        material={Materials.roadMaterials.main}
        position={[5.78, 11.8, 174.74]}
        rotation={[0, 0.49, 0]}
        scale={[5.07, 0.8, 2.23]}
      />
      <group
        position={[-110.31, 18.31, 51.86]}
        rotation={[-1.58, 0, 2.8]}
        scale={[-0.28, -0.3, -0.3]}
      >
        <mesh geometry={nodes.Mesh273.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh273_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-104.87, 25.02, 36.72]}
        rotation={[-1.57, 0, -1.91]}
        scale={[0.29, 0.3, 0.3]}
      >
        <mesh geometry={nodes.Mesh279.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh279_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-107.31, 23.77, 43.45]}
        rotation={[Math.PI, -1.23, Math.PI]}
        scale={[7.96, 1.31, 13.72]}
      >
        <mesh geometry={nodes.Cube002_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube002_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={Materials.floorMaterial}
        position={[-107.36, 17.84, 43.59]}
        rotation={[Math.PI, -1.23, Math.PI]}
        scale={[0.35, 6.15, 12.08]}
      />
      <group
        position={[-107.71, 19.75, 43.31]}
        rotation={[Math.PI, -1.23, Math.PI]}
        scale={[7.81, 2.74, 13.72]}
      >
        <mesh geometry={nodes.Cube004_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube004_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-99.34, 12.3, 64.06]} rotation={[Math.PI / 2, 0, 2.3]} scale={0.49}>
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere001_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-95.78, 12.14, 63.92]} rotation={[Math.PI / 2, 0, 2.16]} scale={0.34}>
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere001_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.long_wide_drawer_v156_f118_Sphere001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-95.81, 13.16, 54.15]} rotation={[Math.PI / 2, 0, -1.13]} scale={0.49}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-91.84, 13.16, 84.96]} rotation={[Math.PI / 2, 0, -0.73]} scale={0.49}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-94.72, 12.79, 88.01]} rotation={[Math.PI / 2, 0, -1.11]} scale={0.34}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-97.44, 12.76, 63.07]} rotation={[Math.PI / 2, 0, -1.98]} scale={0.34}>
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.shelving2_v562_f346_Sphere002_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-106.75, 23.46, 95.88]} rotation={[Math.PI, -0.37, Math.PI]} scale={0.04}>
        <mesh geometry={nodes.Mesh008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-100.35, 17.77, 93.51]}
        rotation={[-Math.PI, 1.2, -Math.PI]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh geometry={nodes.Mesh009.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-109.11, 14.28, 96.64]} rotation={[0, 0.37, 0]} scale={[7.49, 2.54, 10]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube006_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-109.25, 19.86, 96.96]} rotation={[0, 0.37, 0]} scale={[7.64, 3.05, 10.1]}>
        <mesh geometry={nodes.Cube007.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube007_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Wagon_Body001.geometry}
        material={Materials.floorMaterial}
        position={[-95.27, 12.45, 112.23]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <group position={[-93.23, 13.53, 108.02]} rotation={[-Math.PI, 0.45, -Math.PI]} scale={0}>
        <mesh geometry={nodes.Mesh239.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Mesh239_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Wagon_Body005.geometry}
        material={Materials.floorMaterial}
        position={[-91.33, 13.31, 104.11]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body014.geometry}
        material={Materials.floorMaterial}
        position={[-92.22, 13.63, 110.04]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body017.geometry}
        material={materials.Vitre}
        position={[-92.62, 14.09, 106.76]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body026.geometry}
        material={Materials.floorMaterial}
        position={[-92.35, 13.87, 106.32]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body027.geometry}
        material={Materials.floorMaterial}
        position={[-95.6, 13.91, 112.31]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body029.geometry}
        material={Materials.floorMaterial}
        position={[-93.13, 14.17, 107.83]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body031.geometry}
        material={Materials.floorMaterial}
        position={[-91.48, 13.19, 104.43]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body034.geometry}
        material={Materials.floorMaterial}
        position={[-95.3, 13.34, 112.29]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wagon_Body036.geometry}
        material={Materials.floorMaterial}
        position={[-93.32, 12.29, 108.21]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A002.geometry}
        material={Materials.floorMaterial}
        position={[-93.32, 12.5, 108.21]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A003.geometry}
        material={Materials.floorMaterial}
        position={[-93.32, 12.5, 108.21]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A004.geometry}
        material={Materials.floorMaterial}
        position={[-93.32, 12.5, 108.21]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Wheel_A001004.geometry}
        material={Materials.floorMaterial}
        position={[-93.32, 12.5, 108.21]}
        rotation={[-Math.PI, 0.45, -Math.PI]}
        scale={0}
      />
      <group
        position={[-89.6, 13.55, 82.28]}
        rotation={[Math.PI / 2, 0, -1.5]}
        scale={[0.34, 0.34, 0.4]}
      >
        <mesh
          geometry={nodes.shelving1_v359_f350_Sphere013_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.shelving1_v359_f350_Sphere013_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={Materials.floorMaterial}
        position={[-97.5, 15.29, 86.56]}
        rotation={[-Math.PI, 0.08, -Math.PI]}
        scale={2.6}
      />
      <group position={[-93.6, 11.88, 79.05]} rotation={[-Math.PI, 0.11, -Math.PI]} scale={0.47}>
        <mesh geometry={nodes.Plane008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-96.02, 10.01, 60.94]}
        rotation={[-Math.PI, 1.21, -Math.PI]}
        scale={[0.29, 0.72, 0.29]}
      >
        <mesh geometry={nodes.Plane008.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Plane008_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-100.06, 12.35, 87.32]} rotation={[0, 0.24, 0]} scale={[0.09, 1.45, 0.09]}>
        <mesh geometry={nodes.Cylinder031.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cylinder031_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={Materials.floorMaterial}
        position={[-99.76, 13.57, 84.29]}
        rotation={[-Math.PI, 0.08, -Math.PI]}
        scale={[0.03, 1.85, 0.03]}
      />
      <group
        position={[-99.4, 13.67, 86.47]}
        rotation={[0, -0.18, -0.6]}
        scale={[1.13, 0.13, 1.61]}
      >
        <mesh geometry={nodes.Cube034.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube034_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group
        position={[-96.48, 13.71, 59.7]}
        rotation={[-0.04, -1.11, -0.67]}
        scale={[1.13, 0.13, 1.61]}
      >
        <mesh geometry={nodes.Cube034.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cube034_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-89.13, 12.26, 88.2]} rotation={[Math.PI / 2, 0, 1.77]} scale={0.37}>
        <mesh
          geometry={nodes.box_with_one_handle_v44_f30_Sphere016_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box_with_one_handle_v44_f30_Sphere016_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-89.59, 12.16, 89.44]} rotation={[Math.PI / 2, 0, 1.99]} scale={0.34}>
        <mesh
          geometry={nodes.box_with_mesh_v602_f324_Sphere012_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box_with_mesh_v602_f324_Sphere012_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-88.67, 12.13, 85.26]} rotation={[Math.PI / 2, 0, 1.63]} scale={0.44}>
        <mesh
          geometry={nodes.box7_v140_f78_Sphere017_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box7_v140_f78_Sphere017_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-88.83, 12.23, 84.1]} rotation={[Math.PI / 2, 0, 1.63]} scale={0.44}>
        <mesh
          geometry={nodes.box6_v34_f19_Sphere015_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box6_v34_f19_Sphere015_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-89.63, 12.09, 86.88]} rotation={[Math.PI / 2, 0, 1.92]} scale={0.34}>
        <mesh
          geometry={nodes.box5_540_f570_Sphere010_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box5_540_f570_Sphere010_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-91.09, 12.15, 91.04]} rotation={[Math.PI / 2, 0, -0.78]} scale={0.49}>
        <mesh
          geometry={nodes.box3_v108_f74_Sphere004_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box3_v108_f74_Sphere004_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group
        position={[-90.26, 15.81, 83.19]}
        rotation={[-Math.PI, 0.11, -Math.PI]}
        scale={[0.47, 0.55, 0.47]}
      >
        <mesh geometry={nodes.Cylinder011_1.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={Materials.outlineMaterial} />
      </group>
      <mesh
        geometry={nodes.Bar_3002.geometry}
        material={Materials.floorMaterial}
        position={[-94.7, 16.07, 57.99]}
        rotation={[-Math.PI, 1.21, -Math.PI]}
        scale={[0.29, 0.85, 0.29]}
      />
      <group position={[-95.53, 13.87, 59.19]} rotation={[1.94, -0.2, 2.7]} scale={0.34}>
        <mesh
          geometry={nodes.box4_v95_f58_Sphere001_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box4_v95_f58_Sphere001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-95.73, 14.22, 58.74]} rotation={[1.99, -0.23, 2.71]} scale={0.34}>
        <mesh
          geometry={nodes.box4_v95_f58_Sphere001_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.box4_v95_f58_Sphere001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
      <group position={[-95.66, 12.35, 58.91]} rotation={[0, -0.69, 0]} scale={[0.09, 1.37, 0.09]}>
        <mesh geometry={nodes.Cylinder028.geometry} material={Materials.floorMaterial} />
        <mesh geometry={nodes.Cylinder028_1.geometry} material={Materials.outlineMaterial} />
      </group>
      <group position={[-95.21, 12.1, 61.59]} rotation={[Math.PI / 2, 0, 2.49]} scale={0.34}>
        <mesh
          geometry={nodes.long_box_v124_f96__Sphere001_1.geometry}
          material={Materials.floorMaterial}
        />
        <mesh
          geometry={nodes.long_box_v124_f96__Sphere001_2.geometry}
          material={Materials.outlineMaterial}
        />
      </group>
    </group>
  )
}
