/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/assets/scenes/scene_1.2.glb --transform
*/

import React from "react"
import { useGLTF, PerspectiveCamera, useTexture } from "@react-three/drei"
import { DoubleSide, MeshToonMaterial, NearestFilter } from "three"

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/scenes/scene_1.2-transformed.glb")
  console.log(materials)
  console.log(nodes)
  const toonThreeTone = useTexture("/assets/materials/toon/threeTone.jpg")
  toonThreeTone.minFilter = NearestFilter
  toonThreeTone.magFilter = NearestFilter
  const toonFiveTone = useTexture("/assets/materials/toon/fiveTone.jpg")
  toonFiveTone.minFilter = NearestFilter
  toonFiveTone.magFilter = NearestFilter

  const floorMaterial = new MeshToonMaterial({
    color: "#FDEAD2",
    gradientMap: toonFiveTone,
  })

  const roadMaterial = new MeshToonMaterial({
    color: "#F1DFC9",
    side: DoubleSide,
  })

  const fenceMaterial = new MeshToonMaterial({
    color: "#8D8A85",
    gradientMap: toonFiveTone,
  })

  const leafMaterial = new MeshToonMaterial({
    color: "#4F7552",
    gradientMap: toonFiveTone,
  })

  const treeMaterial = new MeshToonMaterial({
    color: "#704D46",
    gradientMap: toonThreeTone,
  })

  const stoneMaterial = new MeshToonMaterial({
    color: "#8D8A85",
    gradientMap: toonFiveTone,
  })

  const cloudMaterial = new MeshToonMaterial({
    color: "#C3FDFD",
    gradientMap: toonThreeTone
  })

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={32.27}
        position={[-8.29, 16.58, -89.6]}
        rotation={[-0.1, 0.16, 0.03]}
      />
      <directionalLight intensity={1.5} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[91.19, 10.23, -490.8]} rotation={[Math.PI / 2, 0, -0.44]} scale={0}>
        <mesh geometry={nodes.Mesh009.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.Material} />
      </group>
      <group position={[-48.82, 8.77, -480.22]} rotation={[Math.PI / 2, 0, 0.88]} scale={0.01}>
        <mesh geometry={nodes.Mesh009.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-167.18, 11.94, -489.48]}
        rotation={[Math.PI / 2, 0, 0.61]}
        scale={[0, 0, 0.01]}
      >
        <mesh geometry={nodes.Mesh009.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.Material} />
      </group>
      <group position={[-10.25, 11.02, -315.7]} scale={[174.33, 43.66, 73.17]}>
        <mesh geometry={nodes.Plane004.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.Material} />
      </group>
      <group position={[73.5, 10.4, -474.26]} rotation={[Math.PI / 2, 0, -0.19]} scale={0.01}>
        <mesh geometry={nodes.Mesh001.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-96.57, -12.15, -444.58]}
        rotation={[Math.PI / 2, 0, -0.43]}
        scale={[0.02, 0.02, 0.03]}
      >
        <mesh geometry={nodes.Mesh010.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Mesh010_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-180.98, 8.2, -424.67]}
        rotation={[Math.PI / 2, 0, -1.43]}
        scale={[0.02, 0.02, 0.03]}
      >
        <mesh geometry={nodes.Mesh008.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.Material} />
      </group>
      <mesh
        geometry={nodes.Fond_color.geometry}
        material={materials["Material.030"]}
        position={[-106.78, 27.75, -554.83]}
        rotation={[1.35, 0, 0]}
        scale={[475.89, 185.83, 185.83]}
      />
      <mesh
        geometry={nodes.Cloud_2.geometry}
        material={cloudMaterial}
        position={[-274.4, 79.87, -463.85]}
        rotation={[0, 1.57, 0]}
        scale={169.33}
      />
      <mesh
        geometry={nodes.Cloud_1.geometry}
        material={cloudMaterial}
        position={[23.51, 72.9, -510.34]}
        rotation={[0, 1.57, 0]}
        scale={169.33}
      />
      <group position={[-20.01, 12.36, -129.87]} rotation={[0.43, 0, 0]} scale={[0.1, 0.1, 0.18]}>
        <mesh geometry={nodes.Sphere_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-19.41, 12.31, -110.76]}
        rotation={[0.01, 0.02, 0.08]}
        scale={[0.43, 0.22, 0.39]}
      >
        <mesh geometry={nodes.Sphere001_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-19.84, 12.41, -130.07]}
        rotation={[-0.14, 0.71, 1.95]}
        scale={[0.06, 0.06, 0.11]}
      >
        <mesh geometry={nodes.Sphere002_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials.Material} />
      </group>
      <group position={[-107.09, 0, -18.42]}>
        <mesh geometry={nodes.Cube048_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube048_2.geometry} material={materials.Material} />
      </group>
      <group position={[-33.96, 12.22, -127.76]} rotation={[-0.06, 0.27, -0.3]} scale={0.6}>
        <mesh geometry={nodes.Cube046_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Cube046_2.geometry} material={materials.Material} />
      </group>
      <group position={[-1.61, 11.19, -103.34]} rotation={[0, 0.06, 0]} scale={[1.24, 0.87, 0.87]}>
        <mesh geometry={nodes.Cube067_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Cube067_2.geometry} material={materials.Material} />
      </group>
      <group position={[-97.3, 0, -50.96]}>
        <mesh geometry={nodes.Cube066_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube066_2.geometry} material={materials.Material} />
      </group>
      <group position={[-89.57, 0, -43.61]}>
        <mesh geometry={nodes.Cube057_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube057_2.geometry} material={materials.Material} />
      </group>
      <group position={[-83.04, 0, -34.52]} rotation={[0, 0, 0.15]}>
        <mesh geometry={nodes.Cube051_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube051_2.geometry} material={materials.Material} />
      </group>
      <group position={[-0.31, 11.2, -159.74]} scale={0.37}>
        <mesh geometry={nodes.Cube053_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Cube053_2.geometry} material={materials.Material} />
      </group>
      <group position={[-70.78, 0, -19.78]}>
        <mesh geometry={nodes.Cube050_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube050_2.geometry} material={materials.Material} />
      </group>
      <group position={[-24.13, 11.11, -144.45]} rotation={[0, 0.42, 0]} scale={0.61}>
        <mesh geometry={nodes.Cube054_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Cube054_2.geometry} material={materials.Material} />
      </group>
      <group position={[-32.06, 11.87, -127.62]} rotation={[0, 0.6, 0]} scale={0.35}>
        <mesh geometry={nodes.Cube001_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-32.63, 12.2, -125.61]}
        rotation={[0.01, 0.02, 0.08]}
        scale={[0.34, 0.17, 0.31]}
      >
        <mesh geometry={nodes.Sphere003_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={materials.Material} />
      </group>
      <group position={[-8.03, 12.54, -98.49]} rotation={[-1.6, 0.25, -0.28]} scale={0.56}>
        <mesh geometry={nodes.Cube008_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-18.23, 12.29, -105.67]}
        rotation={[-0.37, 0.01, 0.02]}
        scale={[0.13, 0.1, 0.18]}
      >
        <mesh geometry={nodes.Sphere004_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Sphere004_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-12.41, 12.54, -151.27]}
        rotation={[-2.81, 1.46, 2.81]}
        scale={[0.43, 0.1, 0.19]}
      >
        <mesh geometry={nodes.Sphere005_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Sphere005_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-12.69, 12.54, -150.46]}
        rotation={[-2.81, 1.46, 2.81]}
        scale={[0.21, 0.05, 0.13]}
      >
        <mesh geometry={nodes.Sphere006_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Sphere006_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-11.97, 12.56, -151.18]}
        rotation={[-0.11, 0.94, 2.53]}
        scale={[0.06, 0.06, 0.11]}
      >
        <mesh geometry={nodes.Sphere007_1.geometry} material={stoneMaterial} />
        <mesh geometry={nodes.Sphere007_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-10.25, 12.07, -170.05]}
        rotation={[0, 0, -Math.PI]}
        scale={[-174.33, -26.31, -73.17]}
      >
        <mesh geometry={nodes.Plane002.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-13.95, 12.12, -167.19]}
        rotation={[-1.56, -0.04, -0.24]}
        scale={[1.42, 2.09, 0.37]}
      >
        <mesh geometry={nodes.Cube013_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-6.25, 12.12, -153.82]}
        rotation={[-1.56, -0.04, -0.24]}
        scale={[0.9, 1.32, 0.42]}
      >
        <mesh geometry={nodes.Cube014_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-8.54, 12.01, -191.31]}
        rotation={[-1.6, -0.02, -1.54]}
        scale={[0.87, 0.59, 0.42]}
      >
        <mesh geometry={nodes.Cube015_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-7.58, 12.68, -190.9]}
        rotation={[-2.85, -0.35, 3.07]}
        scale={[0.16, 0.1, 0.19]}
      >
        <mesh geometry={nodes.Sphere008_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Sphere008_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-14.51, 12.52, -179.2]}
        rotation={[-1.56, -0.04, -0.24]}
        scale={[0.48, 1.01, 0.18]}
      >
        <mesh geometry={nodes.Cube016_1.geometry} material={floorMaterial} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-4.14, 12.86, -96.88]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={[-4.09, -3.28, -3.74]}
      >
        <mesh geometry={nodes.Cube119_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube119_2.geometry} material={materials.Material} />
      </group>
      <group position={[-17.76, 19.34, -134.81]} scale={[0.49, 0.37, 0.54]}>
        <mesh geometry={nodes.Cube088_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube088_2.geometry} material={materials.Material} />
      </group>
      <group position={[-16.29, 18.57, -137.83]} scale={[0.49, 0.37, 0.54]}>
        <mesh geometry={nodes.Cube089_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube089_2.geometry} material={materials.Material} />
      </group>
      <group position={[-21.35, 18.77, -138.25]} rotation={[0, -0.01, 0.03]} scale={0.54}>
        <mesh geometry={nodes.Cube091_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube091_2.geometry} material={materials.Material} />
      </group>
      <group position={[-22.62, 19.43, -134.69]} rotation={[0, -0.18, 0.03]} scale={0.54}>
        <mesh geometry={nodes.Cube092_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube092_2.geometry} material={materials.Material} />
      </group>
      <group position={[-27.12, 18.72, -135.13]} rotation={[0, -0.01, 0.03]} scale={0.54}>
        <mesh geometry={nodes.Cube093_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube093_2.geometry} material={materials.Material} />
      </group>
      <group position={[-21.47, 16.95, -135.88]} scale={0.54}>
        <mesh geometry={nodes.Cube094_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube094_2.geometry} material={materials.Material} />
      </group>
      <group position={[-23.6, 13.45, -108]} scale={0.55}>
        <mesh geometry={nodes.Cube118_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube118_2.geometry} material={materials.Material} />
      </group>
      <group position={[-21.87, 20.41, -105.83]} rotation={[0, 1.25, 0]} scale={[0.49, 0.55, 0.78]}>
        <mesh geometry={nodes.Cube120_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube120_2.geometry} material={materials.Material} />
      </group>
      <group position={[-22.39, 19.2, -109.49]} rotation={[0, 1.25, 0]} scale={[0.49, 0.55, 0.78]}>
        <mesh geometry={nodes.Cube121_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube121_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-19.95, 17.74, -107.42]}
        rotation={[-Math.PI, 0.82, -Math.PI]}
        scale={[0.69, 0.46, 0.94]}
      >
        <mesh geometry={nodes.Cube122_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube122_2.geometry} material={materials.Material} />
      </group>
      <group position={[69.04, 12.68, -371.15]} scale={0.55}>
        <mesh geometry={nodes.Cube002_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.Material} />
      </group>
      <group position={[70.77, 19.54, -368.98]} rotation={[0, 1.25, 0]} scale={[0.49, 0.55, 0.78]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Material} />
      </group>
      <group position={[70.25, 18.43, -372.64]} rotation={[0, 1.25, 0]} scale={[0.49, 0.55, 0.78]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[72.69, 16.97, -370.57]}
        rotation={[-Math.PI, 0.82, -Math.PI]}
        scale={[0.69, 0.46, 0.94]}
      >
        <mesh geometry={nodes.Cube005_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Material} />
      </group>
      <group position={[3.31, 12.35, -209.4]} scale={[0.25, 0.29, 0.29]}>
        <mesh geometry={nodes.Cube087_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube087_2.geometry} material={materials.Material} />
      </group>
      <group position={[3.93, 12.35, -209.65]} rotation={[-0.02, 0.41, 0.07]} scale={0.22}>
        <mesh geometry={nodes.Cube099_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube099_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-20.33, 12.57, -106.51]}
        rotation={[-2.82, 0.59, 3.1]}
        scale={[0.49, 0.49, 0.63]}
      >
        <mesh geometry={nodes.Cube084_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube084_2.geometry} material={materials.Material} />
      </group>
      <group position={[-27.59, 17.95, -227.11]} rotation={[0, -0.37, 0]} scale={[0.8, 0.61, 0.8]}>
        <mesh geometry={nodes.Cube011_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.Material} />
      </group>
      <group position={[-27.59, 13.22, -226.57]} scale={0.54}>
        <mesh geometry={nodes.Cube039_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube039_2.geometry} material={materials.Material} />
      </group>
      <group position={[63.29, 11.43, -363.39]} scale={0.61}>
        <mesh geometry={nodes.Cube024_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.Material} />
      </group>
      <mesh
        geometry={nodes.Cube024.geometry}
        material={leafMaterial}
        position={[65.41, 20.32, -361.59]}
        scale={0.38}
      />
      <group position={[59.15, 26.25, -360.23]} rotation={[0.17, -0.29, -0.19]} scale={0.44}>
        <mesh geometry={nodes.Cube027_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials.Material} />
      </group>
      <group position={[59.13, 23.12, -363.8]} rotation={[0, 0, 0.18]} scale={[0.44, 0.44, 0.53]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials.Material} />
      </group>
      <group position={[65.62, 24.09, -361.9]} rotation={[0, 0, -0.08]} scale={[0.4, 0.45, 0.63]}>
        <mesh geometry={nodes.Cube029_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials.Material} />
      </group>
      <group position={[63.01, 26.2, -361.26]} scale={[0.64, 0.44, 0.56]}>
        <mesh geometry={nodes.Cube104_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube104_2.geometry} material={materials.Material} />
      </group>
      <group position={[69.67, 11.51, -416.59]} scale={0.5}>
        <mesh geometry={nodes.Cube_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Material} />
      </group>
      <group position={[54.83, 11.47, -407.84]} scale={0.61}>
        <mesh geometry={nodes.Cube010_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.Material} />
      </group>
      <group position={[54, 18.95, -414.84]} scale={[0.5, 0.5, 0.59]}>
        <mesh geometry={nodes.Cube042_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube042_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-56.13, 15.97, -525.09]}
        rotation={[0, -1.31, -Math.PI]}
        scale={[-0.44, -0.44, -0.52]}
      >
        <mesh geometry={nodes.Cube042_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube042_2.geometry} material={materials.Material} />
      </group>
      <group position={[51.02, 14.7, -415.39]} scale={[0.62, 0.62, 0.86]}>
        <mesh geometry={nodes.Cube041_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube041_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[55.17, 17.52, -414.82]}
        rotation={[0.09, 1.17, -0.14]}
        scale={[0.74, 0.62, 1.2]}
      >
        <mesh geometry={nodes.Cube017_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials.Material} />
      </group>
      <group position={[51.3, 17.79, -415.5]} rotation={[1.72, -1.38, 1.75]} scale={0.55}>
        <mesh geometry={nodes.Cube018_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials.Material} />
      </group>
      <group position={[54, 11.11, -416.32]} scale={0.5}>
        <mesh geometry={nodes.Cube043_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube043_2.geometry} material={materials.Material} />
      </group>
      <group position={[64.39, 18.65, -405.58]} scale={[0.44, 0.5, 0.71]}>
        <mesh geometry={nodes.Cube020_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.Material} />
      </group>
      <group position={[62.09, 17.76, -406.99]} rotation={[0, 0.24, 0]} scale={[0.33, 0.29, 0.51]}>
        <mesh geometry={nodes.Cube021_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials.Material} />
      </group>
      <group position={[68.08, 16.57, -406.48]} rotation={[0, -0.02, 0]} scale={[0.33, 0.29, 0.51]}>
        <mesh geometry={nodes.Cube022_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials.Material} />
      </group>
      <group position={[65.79, 16.57, -407.04]} rotation={[0, 0, 0.32]} scale={[0.26, 0.33, 0.41]}>
        <mesh geometry={nodes.Cube023_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[62.64, 18.78, -389]}
        rotation={[-Math.PI, 1.32, -Math.PI]}
        scale={[0.71, 0.5, 0.62]}
      >
        <mesh geometry={nodes.Cube026_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials.Material} />
      </group>
      <group position={[81.56, 11.95, -409.65]} rotation={[0, 0.54, 0]} scale={0.5}>
        <mesh geometry={nodes.Cube030_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials.Material} />
      </group>
      <group position={[75.89, 17.25, -404.24]} rotation={[0.09, -0.1, 0.2]} scale={0.5}>
        <mesh geometry={nodes.Cube031_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[80.3, 19.5, -407.25]}
        rotation={[0.15, -1.05, 0.15]}
        scale={[0.55, 0.55, 0.89]}
      >
        <mesh geometry={nodes.Cube032_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials.Material} />
      </group>
      <group position={[85.49, 19.51, -411.39]} rotation={[0, 0.18, 0]} scale={[0.58, 0.41, 0.57]}>
        <mesh geometry={nodes.Cube033_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[81.43, 21.53, -409.93]}
        rotation={[0.21, -0.27, 0.07]}
        scale={[0.48, 0.56, 0.77]}
      >
        <mesh geometry={nodes.Cube034_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube034_2.geometry} material={materials.Material} />
      </group>
      <group position={[80.96, 17.72, -410.18]} rotation={[0, 0.54, 0]} scale={[0.44, 0.37, 0.37]}>
        <mesh geometry={nodes.Cube035_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube035_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[82.16, 18.42, -410.9]}
        rotation={[0, 0.54, -0.15]}
        scale={[0.44, 0.37, 0.42]}
      >
        <mesh geometry={nodes.Cube036_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube036_2.geometry} material={materials.Material} />
      </group>
      <mesh
        geometry={nodes.Cube036.geometry}
        material={leafMaterial}
        position={[81.23, 20.76, -410.77]}
        rotation={[-0.03, 0.43, 0.03]}
        scale={[0.36, 0.4, 0.34]}
      />
      <mesh
        geometry={nodes.Cube111.geometry}
        material={leafMaterial}
        position={[-46.48, 17.58, -502.6]}
        rotation={[2.98, -1.4, -0.14]}
        scale={[-0.32, -0.36, -0.3]}
      />
      <group
        position={[78.4, 18.55, -408.99]}
        rotation={[-0.07, 0.73, -0.16]}
        scale={[0.41, 0.25, 0.36]}
      >
        <mesh geometry={nodes.Cube038_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials.Material} />
      </group>
      <group position={[81.97, 20.83, -421.43]} rotation={[0, -0.81, 0]} scale={[1.23, 0.94, 1.23]}>
        <mesh geometry={nodes.Cube040_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube040_2.geometry} material={materials.Material} />
      </group>
      <group position={[57.09, 11.89, -399.82]} rotation={[0, 0.33, 0]} scale={0.45}>
        <mesh geometry={nodes.Cube068_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube068_2.geometry} material={materials.Material} />
      </group>
      <group position={[88.51, 11.85, -401.82]} rotation={[0, 0.44, 0]} scale={0.71}>
        <mesh geometry={nodes.Cube069_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube069_2.geometry} material={materials.Material} />
      </group>
      <group position={[77.41, 11.44, -396.89]} scale={0.5}>
        <mesh geometry={nodes.Cube070_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube070_2.geometry} material={materials.Material} />
      </group>
      <group position={[63.84, 11.51, -398.86]} rotation={[0, 0.72, 0]} scale={[0.46, 0.41, 0.46]}>
        <mesh geometry={nodes.Cube071_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube071_2.geometry} material={materials.Material} />
      </group>
      <group position={[79.96, 15.46, -396.53]} scale={[0.56, 0.5, 0.36]}>
        <mesh geometry={nodes.Cube072_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube072_2.geometry} material={materials.Material} />
      </group>
      <group position={[73.91, 17.84, -396.65]} scale={[0.56, 0.52, 0.38]}>
        <mesh geometry={nodes.Cube073_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube073_2.geometry} material={materials.Material} />
      </group>
      <group position={[79.06, 21.72, -395.98]} scale={[0.64, 0.54, 0.69]}>
        <mesh geometry={nodes.Cube074_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube074_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[76.32, 20.45, -397.86]}
        rotation={[-0.17, 1, 0.08]}
        scale={[0.64, 0.54, 0.69]}
      >
        <mesh geometry={nodes.Cube075_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube075_2.geometry} material={materials.Material} />
      </group>
      <group position={[63.14, 15.65, -399.37]} rotation={[0, 0.72, 0]} scale={[0.45, 0.37, 0.37]}>
        <mesh geometry={nodes.Cube076_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube076_2.geometry} material={materials.Material} />
      </group>
      <group position={[65.09, 18.88, -397.79]} rotation={[0, 0.72, 0]} scale={[0.45, 0.37, 0.37]}>
        <mesh geometry={nodes.Cube077_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials.Material} />
      </group>
      <group position={[66.51, 19.1, -400.28]} rotation={[0, 0.27, -0.08]} scale={0.74}>
        <mesh geometry={nodes.Cube078_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube078_2.geometry} material={materials.Material} />
      </group>
      <group position={[58.04, 18.21, -401.66]} rotation={[0.02, 0.34, -0.01]} scale={0.5}>
        <mesh geometry={nodes.Cube061_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube061_2.geometry} material={materials.Material} />
      </group>
      <group position={[57.25, 17.28, -401.17]} rotation={[0.02, 0.34, -0.01]} scale={0.32}>
        <mesh geometry={nodes.Cube062_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube062_2.geometry} material={materials.Material} />
      </group>
      <group position={[58.67, 14.86, -400.07]} rotation={[0.02, 0.34, -0.01]} scale={0.21}>
        <mesh geometry={nodes.Cube063_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube063_2.geometry} material={materials.Material} />
      </group>
      <group position={[56.57, 18.33, -398.33]} rotation={[0.02, 0.34, -0.01]} scale={0.5}>
        <mesh geometry={nodes.Cube079_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube079_2.geometry} material={materials.Material} />
      </group>
      <group position={[54.11, 17.72, -397.06]} rotation={[0.02, 0.34, -0.01]} scale={0.5}>
        <mesh geometry={nodes.Cube080_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube080_2.geometry} material={materials.Material} />
      </group>
      <group position={[86.29, 18.43, -400.83]} rotation={[0, 0.44, 0]} scale={0.5}>
        <mesh geometry={nodes.Cube081_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube081_2.geometry} material={materials.Material} />
      </group>
      <group position={[91.1, 19.05, -402.92]} rotation={[0, 0.44, 0]} scale={[0.65, 0.5, 0.73]}>
        <mesh geometry={nodes.Cube082_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube082_2.geometry} material={materials.Material} />
      </group>
      <group position={[88.91, 18.37, -403.46]} rotation={[0, 0.44, 0]} scale={0.44}>
        <mesh geometry={nodes.Cube083_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube083_2.geometry} material={materials.Material} />
      </group>
      <group position={[83.48, 19.27, -421.28]} rotation={[0, -0.44, 0]} scale={0.23}>
        <mesh geometry={nodes.Cube044_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube044_2.geometry} material={materials.Material} />
      </group>
      <group position={[54.83, 16.76, -408.44]} rotation={[0, -0.37, 0]} scale={[0.9, 0.69, 0.9]}>
        <mesh geometry={nodes.Cube045_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube045_2.geometry} material={materials.Material} />
      </group>
      <group position={[78.67, 19.64, -422.72]} rotation={[-2.89, -0.35, -3.02]} scale={0.82}>
        <mesh geometry={nodes.Cube047_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube047_2.geometry} material={materials.Material} />
      </group>
      <group position={[89.91, 11.51, -391.79]} rotation={[0, 0.63, 0]} scale={0.5}>
        <mesh geometry={nodes.Cube009_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.Material} />
      </group>
      <group position={[72.74, 11.51, -389.78]} rotation={[0, 0.08, 0]} scale={0.5}>
        <mesh geometry={nodes.Cube019_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.Material} />
      </group>
      <group position={[62.02, 11.51, -391.18]} rotation={[-Math.PI, 1.32, -Math.PI]} scale={0.71}>
        <mesh geometry={nodes.Cube090_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube090_2.geometry} material={materials.Material} />
      </group>
      <group position={[51.86, 11.51, -389.53]} rotation={[0, 0.63, 0]} scale={0.5}>
        <mesh geometry={nodes.Cube098_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube098_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[54.43, 17.41, -388.98]}
        rotation={[-Math.PI, 1.26, -Math.PI]}
        scale={[0.44, 0.5, 0.71]}
      >
        <mesh geometry={nodes.Cube101_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube101_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-33.8, 14.6, -530.57]}
        rotation={[-Math.PI, 0.05, 0]}
        scale={[-0.4, -0.45, -0.63]}
      >
        <mesh geometry={nodes.Cube101_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube101_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[51.96, 16.74, -391.28]}
        rotation={[-Math.PI, 1.26, -Math.PI]}
        scale={[0.44, 0.5, 0.71]}
      >
        <mesh geometry={nodes.Cube102_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube102_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[54.86, 15.41, -391.07]}
        rotation={[-Math.PI, 0.19, -Math.PI]}
        scale={[0.62, 0.42, 0.86]}
      >
        <mesh geometry={nodes.Cube103_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube103_2.geometry} material={materials.Material} />
      </group>
      <group position={[61.35, 17.86, -391.53]} rotation={[Math.PI, 0.87, -3.03]} scale={0.29}>
        <mesh geometry={nodes.Cube105_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube105_2.geometry} material={materials.Material} />
      </group>
      <group position={[62.26, 18.23, -392.84]} rotation={[-Math.PI, -0.26, -3.03]} scale={0.29}>
        <mesh geometry={nodes.Cube106_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube106_2.geometry} material={materials.Material} />
      </group>
      <group position={[75.89, 19.04, -387.74]} rotation={[0, 0.08, 0]} scale={[0.64, 0.54, 0.69]}>
        <mesh geometry={nodes.Cube107_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube107_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-27.88, 16.05, -512.4]}
        rotation={[0, -1.39, -Math.PI]}
        scale={[-0.57, -0.48, -0.61]}
      >
        <mesh geometry={nodes.Cube107_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube107_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[77.21, 16.31, -389.24]}
        rotation={[0, 0.08, -0.13]}
        scale={[0.46, 0.38, 0.49]}
      >
        <mesh geometry={nodes.Cube108_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube108_2.geometry} material={materials.Material} />
      </group>
      <group position={[68.81, 19.37, -389.07]} rotation={[0.07, 0.09, 0.18]} scale={0.5}>
        <mesh geometry={nodes.Cube109_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube109_2.geometry} material={materials.Material} />
      </group>
      <group position={[86.27, 17.33, -387.05]} rotation={[0, 0.62, 0.03]} scale={0.5}>
        <mesh geometry={nodes.Cube110_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube110_2.geometry} material={materials.Material} />
      </group>
      <group position={[89.93, 17.89, -388.74]} rotation={[0, 0.45, 0.03]} scale={0.5}>
        <mesh geometry={nodes.Cube111_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube111_2.geometry} material={materials.Material} />
      </group>
      <group position={[88.43, 17.73, -392.44]} rotation={[0, 0.62, 0.03]} scale={0.5}>
        <mesh geometry={nodes.Cube112_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube112_2.geometry} material={materials.Material} />
      </group>
      <group position={[92.31, 17.59, -394.65]} rotation={[0, 0.63, 0]} scale={[0.45, 0.34, 0.5]}>
        <mesh geometry={nodes.Cube113_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube113_2.geometry} material={materials.Material} />
      </group>
      <group position={[92.86, 18.31, -391.29]} rotation={[0, 0.63, 0]} scale={[0.45, 0.34, 0.5]}>
        <mesh geometry={nodes.Cube114_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube114_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[76.12, 18.91, -424.65]}
        rotation={[0, 0.01, 0.11]}
        scale={[-0.6, -0.57, -0.79]}
      >
        <mesh geometry={nodes.Cube049_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube049_2.geometry} material={materials.Material} />
      </group>
      <group position={[81.61, 11.51, -422.55]} rotation={[0, -0.44, 0]} scale={[0.5, 0.5, 0.42]}>
        <mesh geometry={nodes.Cube052_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube052_2.geometry} material={materials.Material} />
      </group>
      <group position={[66.02, 16.23, -422.55]} rotation={[-0.01, 0.8, 0.12]} scale={0.26}>
        <mesh geometry={nodes.Cube055_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube055_2.geometry} material={materials.Material} />
      </group>
      <group position={[63.33, 17.3, -420.66]} rotation={[0, 0.35, 0.12]} scale={0.5}>
        <mesh geometry={nodes.Cube056_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube056_2.geometry} material={materials.Material} />
      </group>
      <group position={[65.88, 11.78, -407.72]} scale={0.55}>
        <mesh geometry={nodes.Cube058_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube058_2.geometry} material={materials.Material} />
      </group>
      <group position={[64.27, 11.57, -422.18]} rotation={[0, 0.35, 0.01]} scale={0.5}>
        <mesh geometry={nodes.Cube059_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube059_2.geometry} material={materials.Material} />
      </group>
      <group position={[72.43, 18.5, -415.9]} rotation={[0, -0.37, 0]} scale={0.76}>
        <mesh geometry={nodes.Cube060_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube060_2.geometry} material={materials.Material} />
      </group>
      <group position={[68.71, 19.1, -415.18]} scale={0.82}>
        <mesh geometry={nodes.Cube064_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube064_2.geometry} material={materials.Material} />
      </group>
      <group position={[-54.09, 9.35, -511.23]} rotation={[0, -1.31, -Math.PI]} scale={-0.44}>
        <mesh geometry={nodes.Cube065_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube065_2.geometry} material={materials.Material} />
      </group>
      <group position={[-49.92, 9.32, -525.96]} rotation={[0, -1.31, -Math.PI]} scale={-0.54}>
        <mesh geometry={nodes.Cube085_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube085_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-57.27, 12.19, -527.53]}
        rotation={[0, -1.31, -Math.PI]}
        scale={[-0.55, -0.55, -0.76]}
      >
        <mesh geometry={nodes.Cube095_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube095_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-55.84, 14.7, -524.09]}
        rotation={[-3.1, -0.66, -0.03]}
        scale={[-0.66, -0.55, -1.07]}
      >
        <mesh geometry={nodes.Cube096_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube096_2.geometry} material={materials.Material} />
      </group>
      <group position={[-57.3, 14.94, -527.26]} rotation={[-0.2, 0.28, -3.06]} scale={-0.49}>
        <mesh geometry={nodes.Cube097_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube097_2.geometry} material={materials.Material} />
      </group>
      <group position={[-57.4, 9, -524.76]} rotation={[0, -1.31, -Math.PI]} scale={-0.44}>
        <mesh geometry={nodes.Cube100_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube100_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-45.82, 15.7, -518.26]}
        rotation={[0, -1.31, -Math.PI]}
        scale={[-0.4, -0.45, -0.63]}
      >
        <mesh geometry={nodes.Cube115_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube115_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-47.54, 14.92, -519.91]}
        rotation={[0, -1.56, -Math.PI]}
        scale={[-0.29, -0.26, -0.45]}
      >
        <mesh geometry={nodes.Cube116_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube116_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-45.75, 13.85, -514.88]}
        rotation={[0, -1.3, -Math.PI]}
        scale={[-0.29, -0.26, -0.45]}
      >
        <mesh geometry={nodes.Cube117_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube117_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-46.76, 13.85, -516.72]}
        rotation={[0, -1.31, -2.82]}
        scale={[-0.23, -0.29, -0.36]}
      >
        <mesh geometry={nodes.Cube123_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube123_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-31.96, 15.82, -523.51]}
        rotation={[Math.PI, 0, 0]}
        scale={[-0.63, -0.44, -0.55]}
      >
        <mesh geometry={nodes.Cube124_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube124_2.geometry} material={materials.Material} />
      </group>
      <group position={[-45.43, 9.74, -502.57]} rotation={[Math.PI, -1.28, 0]} scale={-0.44}>
        <mesh geometry={nodes.Cube125_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube125_2.geometry} material={materials.Material} />
      </group>
      <group position={[-42.07, 14.46, -508.67]} rotation={[-0.26, -1.2, 3.08]} scale={-0.44}>
        <mesh geometry={nodes.Cube126_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube126_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-43.66, 16.46, -504.2]}
        rotation={[-0.08, -0.26, -3.14]}
        scale={[-0.49, -0.49, -0.79]}
      >
        <mesh geometry={nodes.Cube127_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube127_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-46.04, 16.47, -498.79]}
        rotation={[0, -1.49, -Math.PI]}
        scale={[-0.52, -0.37, -0.51]}
      >
        <mesh geometry={nodes.Cube128_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube128_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-45.7, 18.26, -502.62]}
        rotation={[-0.38, -1.01, 2.83]}
        scale={[-0.43, -0.5, -0.68]}
      >
        <mesh geometry={nodes.Cube129_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube129_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-46.02, 14.88, -502.96]}
        rotation={[Math.PI, -1.28, 0]}
        scale={[-0.39, -0.33, -0.33]}
      >
        <mesh geometry={nodes.Cube130_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube130_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-46.37, 15.5, -501.77]}
        rotation={[-Math.PI, -1.28, -0.15]}
        scale={[-0.39, -0.33, -0.37]}
      >
        <mesh geometry={nodes.Cube131_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube131_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-45.58, 15.62, -505.44]}
        rotation={[3.02, -1.1, -0.32]}
        scale={[-0.37, -0.22, -0.32]}
      >
        <mesh geometry={nodes.Cube133_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube133_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-55.47, 17.64, -499.55]}
        rotation={[0, -0.5, -Math.PI]}
        scale={[-1.09, -0.83, -1.09]}
      >
        <mesh geometry={nodes.Cube134_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube134_2.geometry} material={materials.Material} />
      </group>
      <group position={[-42.51, 9.69, -525.83]} rotation={[Math.PI, -1.5, 0]} scale={-0.4}>
        <mesh geometry={nodes.Cube135_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube135_2.geometry} material={materials.Material} />
      </group>
      <group position={[-37.13, 9.66, -498.36]} rotation={[Math.PI, -1.39, 0]} scale={-0.63}>
        <mesh geometry={nodes.Cube136_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube136_2.geometry} material={materials.Material} />
      </group>
      <group position={[-35.4, 9.29, -509.02]} rotation={[0, -1.31, -Math.PI]} scale={-0.44}>
        <mesh geometry={nodes.Cube137_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube137_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-40.17, 9.35, -520.25]}
        rotation={[Math.PI, -1.11, 0]}
        scale={[-0.41, -0.36, -0.41]}
      >
        <mesh geometry={nodes.Cube138_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube138_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-34.51, 12.87, -506.91]}
        rotation={[0, -1.31, -Math.PI]}
        scale={[-0.49, -0.44, -0.32]}
      >
        <mesh geometry={nodes.Cube139_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube139_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-35.99, 14.98, -512.08]}
        rotation={[0, -1.31, -Math.PI]}
        scale={[-0.49, -0.46, -0.34]}
      >
        <mesh geometry={nodes.Cube140_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube140_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-34.25, 18.43, -507.81]}
        rotation={[0, -1.31, -Math.PI]}
        scale={[-0.57, -0.48, -0.61]}
      >
        <mesh geometry={nodes.Cube141_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube141_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-36.48, 17.3, -509.74]}
        rotation={[3, -0.82, -0.16]}
        scale={[-0.57, -0.48, -0.61]}
      >
        <mesh geometry={nodes.Cube142_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube142_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-40.76, 13.04, -520.73]}
        rotation={[Math.PI, -1.11, 0]}
        scale={[-0.4, -0.33, -0.33]}
      >
        <mesh geometry={nodes.Cube143_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube143_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-38.96, 15.91, -519.41]}
        rotation={[Math.PI, -1.11, 0]}
        scale={[-0.4, -0.33, -0.33]}
      >
        <mesh geometry={nodes.Cube144_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube144_2.geometry} material={materials.Material} />
      </group>
      <group position={[-40.78, 16.1, -517.63]} rotation={[-Math.PI, -1.56, -0.08]} scale={-0.66}>
        <mesh geometry={nodes.Cube145_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube145_2.geometry} material={materials.Material} />
      </group>
      <group position={[-43.88, 15.31, -524.6]} rotation={[-2.97, -1.49, 0.17]} scale={-0.44}>
        <mesh geometry={nodes.Cube146_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube146_2.geometry} material={materials.Material} />
      </group>
      <group position={[-43.64, 14.49, -525.39]} rotation={[-2.97, -1.49, 0.17]} scale={-0.29}>
        <mesh geometry={nodes.Cube147_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube147_2.geometry} material={materials.Material} />
      </group>
      <group position={[-42.37, 12.33, -524.42]} rotation={[-2.97, -1.49, 0.17]} scale={-0.19}>
        <mesh geometry={nodes.Cube148_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube148_2.geometry} material={materials.Material} />
      </group>
      <group position={[-41.35, 15.42, -526.62]} rotation={[-2.97, -1.49, 0.17]} scale={-0.44}>
        <mesh geometry={nodes.Cube149_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube149_2.geometry} material={materials.Material} />
      </group>
      <group position={[-40.81, 14.87, -529.02]} rotation={[-2.97, -1.49, 0.17]} scale={-0.44}>
        <mesh geometry={nodes.Cube150_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube150_2.geometry} material={materials.Material} />
      </group>
      <group position={[-36.78, 15.51, -500.49]} rotation={[Math.PI, -1.39, 0]} scale={-0.44}>
        <mesh geometry={nodes.Cube151_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube151_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-37.49, 16.06, -495.89]}
        rotation={[Math.PI, -1.39, 0]}
        scale={[-0.58, -0.44, -0.65]}
      >
        <mesh geometry={nodes.Cube152_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube152_2.geometry} material={materials.Material} />
      </group>
      <group position={[-38.45, 15.45, -497.64]} rotation={[Math.PI, -1.39, 0]} scale={-0.39}>
        <mesh geometry={nodes.Cube153_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube153_2.geometry} material={materials.Material} />
      </group>
      <group position={[-55, 16.25, -498.29]} rotation={[0, -0.87, -Math.PI]} scale={-0.2}>
        <mesh geometry={nodes.Cube154_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube154_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-50.44, 14.03, -525.82]}
        rotation={[0, -0.94, -Math.PI]}
        scale={[-0.8, -0.61, -0.8]}
      >
        <mesh geometry={nodes.Cube155_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube155_2.geometry} material={materials.Material} />
      </group>
      <group position={[-57.33, 16.59, -502.09]} rotation={[1.18, 1.31, 2.01]} scale={-0.73}>
        <mesh geometry={nodes.Cube156_1.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube156_2.geometry} material={materials.Material} />
      </group>
      <group position={[-28.19, 9.35, -499.43]} rotation={[Math.PI, -1.19, 0]} scale={-0.44}>
        <mesh geometry={nodes.Cube157_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube157_2.geometry} material={materials.Material} />
      </group>
      <group position={[-30.34, 9.35, -514.64]} rotation={[0, -1.39, -Math.PI]} scale={-0.44}>
        <mesh geometry={nodes.Cube158_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube158_2.geometry} material={materials.Material} />
      </group>
      <group position={[-33.97, 9.35, -523.55]} rotation={[Math.PI, 0, 0]} scale={-0.63}>
        <mesh geometry={nodes.Cube159_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube159_2.geometry} material={materials.Material} />
      </group>
      <group position={[-34.85, 9.35, -532.65]} rotation={[Math.PI, -1.2, 0]} scale={-0.44}>
        <mesh geometry={nodes.Cube160_1.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube160_2.geometry} material={materials.Material} />
      </group>
      <group
        position={[-36.33, 14, -532.18]}
        rotation={[-Math.PI, 0.05, 0]}
        scale={[-0.4, -0.45, -0.63]}
      >
        <mesh geometry={nodes.Cube162.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube162_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-35.49, 12.82, -529.72]}
        rotation={[-Math.PI, 1.12, 0]}
        scale={[-0.55, -0.38, -0.76]}
      >
        <mesh geometry={nodes.Cube163.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube163_1.geometry} material={materials.Material} />
      </group>
      <group position={[-34.42, 15, -524.05]} rotation={[-Math.PI, 0.45, 0.11]} scale={-0.26}>
        <mesh geometry={nodes.Cube164.geometry} material={treeMaterial} />
        <mesh geometry={nodes.Cube164_1.geometry} material={materials.Material} />
      </group>
      <group position={[-35.34, 15.33, -522.96]} rotation={[0, 1.57, -3.03]} scale={-0.26}>
        <mesh geometry={nodes.Cube165.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube165_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-28.87, 13.63, -510.92]}
        rotation={[0, -1.39, 3.01]}
        scale={[-0.41, -0.34, -0.43]}
      >
        <mesh geometry={nodes.Cube167.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube167_1.geometry} material={materials.Material} />
      </group>
      <group position={[-30.62, 16.35, -518.18]} rotation={[-0.43, -1.39, 2.91]} scale={-0.44}>
        <mesh geometry={nodes.Cube168.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube168_1.geometry} material={materials.Material} />
      </group>
      <group position={[-24.94, 14.53, -503.63]} rotation={[3.14, -1.2, 0.03]} scale={-0.44}>
        <mesh geometry={nodes.Cube169.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube169_1.geometry} material={materials.Material} />
      </group>
      <group position={[-25.56, 15.03, -500.1]} rotation={[3.14, -1.37, 0.03]} scale={-0.44}>
        <mesh geometry={nodes.Cube170.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube170_1.geometry} material={materials.Material} />
      </group>
      <group position={[-29.08, 14.89, -500.55]} rotation={[3.14, -1.2, 0.03]} scale={-0.44}>
        <mesh geometry={nodes.Cube171.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube171_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-30.1, 14.76, -496.72]}
        rotation={[Math.PI, -1.19, 0]}
        scale={[-0.4, -0.31, -0.45]}
      >
        <mesh geometry={nodes.Cube172.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube172_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-27.09, 15.4, -497]}
        rotation={[Math.PI, -1.19, 0]}
        scale={[-0.4, -0.31, -0.45]}
      >
        <mesh geometry={nodes.Cube173.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube173_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-59.56, 15.93, -503.85]}
        rotation={[0, -1.32, -3.03]}
        scale={[0.53, 0.5, 0.7]}
      >
        <mesh geometry={nodes.Cube174.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube174_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-56.51, 9.35, -499.61]}
        rotation={[0, -0.87, -Math.PI]}
        scale={[-0.44, -0.44, -0.37]}
      >
        <mesh geometry={nodes.Cube175.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube175_1.geometry} material={materials.Material} />
      </group>
      <group position={[-60.04, 13.55, -513.02]} rotation={[3.13, -1.03, 0.11]} scale={-0.23}>
        <mesh geometry={nodes.Cube176.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube176_1.geometry} material={materials.Material} />
      </group>
      <group position={[-59.02, 14.5, -515.76]} rotation={[3.13, -1.48, 0.1]} scale={-0.44}>
        <mesh geometry={nodes.Cube177.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube177_1.geometry} material={materials.Material} />
      </group>
      <group position={[-47.32, 9.59, -516.49]} rotation={[0, -1.31, -Math.PI]} scale={-0.49}>
        <mesh geometry={nodes.Cube178.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube178_1.geometry} material={materials.Material} />
      </group>
      <group position={[-60.11, 9.41, -514.6]} rotation={[3.13, -1.48, -0.01]} scale={-0.44}>
        <mesh geometry={nodes.Cube179.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube179_1.geometry} material={materials.Material} />
      </group>
      <group position={[-52.87, 15.57, -509]} rotation={[0, -0.94, -Math.PI]} scale={-0.68}>
        <mesh geometry={nodes.Cube180.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube180_1.geometry} material={materials.Material} />
      </group>
      <group position={[-53.09, 16.1, -512.37]} rotation={[0, -1.31, -Math.PI]} scale={-0.73}>
        <mesh geometry={nodes.Cube181.geometry} material={leafMaterial} />
        <mesh geometry={nodes.Cube181_1.geometry} material={materials.Material} />
      </group>
      <mesh
        geometry={nodes.Route_2003.geometry}
        material={roadMaterial}
        position={[-3.44, 12, -261.49]}
        rotation={[0, 0.52, 0]}
        scale={[2.09, 1, 2.72]}
      />
      <group
        position={[-15.25, 13.36, -122.13]}
        rotation={[Math.PI, -0.1, 0]}
        scale={[-0.01, -0.01, -0.02]}
      >
        <mesh geometry={nodes.Mesh005.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[0.85, 13.19, -207.1]}
        rotation={[0, -0.18, -Math.PI]}
        scale={[-0.01, -0.01, -0.02]}
      >
        <mesh geometry={nodes.Mesh005.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.Material} />
      </group>
      <group position={[-15.12, 17.44, -145.84]} rotation={[0.02, -0.36, 0.03]} scale={0.01}>
        <mesh geometry={nodes.Mesh003.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Material} />
      </group>
      <group position={[-8.9, 17.41, -116.02]} rotation={[3.13, -0.37, -0.03]} scale={-0.01}>
        <mesh geometry={nodes.Mesh003.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Material} />
      </group>
      <group position={[-3.29, 16.56, -210.32]} rotation={[Math.PI, -0.18, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh003.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Material} />
      </group>
      <group
        position={[-10.44, 13.37, -121.5]}
        rotation={[0, 0.1, Math.PI]}
        scale={[-0.01, -0.01, -0.02]}
      >
        <mesh geometry={nodes.Mesh006.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials.Material} />
      </group>
      <group position={[-7.23, 19.63, -153.96]} rotation={[-0.02, -0.91, -0.03]} scale={0.01}>
        <mesh geometry={nodes.Mesh007.geometry} material={fenceMaterial} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload("/scene_1.2-transformed.glb")
